(define (problem roverprob5142) (:domain rover)
(:objects
	camera1 - camera
	camera6 - camera
	camera3 - camera
	rover7store - store
	rover3store - store
	waypoint19 - waypoint
	rover0store - store
	colour - mode
	objective4 - objective
	waypoint37 - waypoint
	camera2 - camera
	rover4store - store
	objective6 - objective
	camera7 - camera
	rover1 - rover
	waypoint10 - waypoint
	high_res - mode
	waypoint9 - waypoint
	camera10 - camera
	rover6store - store
	rover7 - rover
	waypoint25 - waypoint
	waypoint16 - waypoint
	waypoint27 - waypoint
	waypoint26 - waypoint
	waypoint21 - waypoint
	waypoint20 - waypoint
	waypoint23 - waypoint
	waypoint22 - waypoint
	waypoint11 - waypoint
	waypoint29 - waypoint
	waypoint28 - waypoint
	objective9 - objective
	camera4 - camera
	waypoint8 - waypoint
	objective8 - objective
	waypoint6 - waypoint
	waypoint7 - waypoint
	low_res - mode
	waypoint5 - waypoint
	waypoint2 - waypoint
	waypoint3 - waypoint
	waypoint0 - waypoint
	rover2store - store
	waypoint4 - waypoint
	waypoint13 - waypoint
	rover2 - rover
	rover3 - rover
	rover0 - rover
	general - lander
	rover6 - rover
	camera8 - camera
	rover4 - rover
	rover5 - rover
	waypoint18 - waypoint
	camera9 - camera
	camera5 - camera
	waypoint1 - waypoint
	rover5store - store
	camera0 - camera
	objective0 - objective
	objective3 - objective
	objective2 - objective
	objective5 - objective
	waypoint15 - waypoint
	objective7 - objective
	waypoint17 - waypoint
	waypoint36 - waypoint
	objective1 - objective
	waypoint34 - waypoint
	waypoint35 - waypoint
	waypoint32 - waypoint
	waypoint33 - waypoint
	waypoint30 - waypoint
	waypoint31 - waypoint
	waypoint24 - waypoint
	rover1store - store
	waypoint14 - waypoint
	waypoint12 - waypoint
	waypoint38 - waypoint
	waypoint39 - waypoint
)
(:init
	(visible waypoint0 waypoint3)
	(visible waypoint3 waypoint0)
	(visible waypoint0 waypoint4)
	(visible waypoint4 waypoint0)
	(visible waypoint0 waypoint27)
	(visible waypoint27 waypoint0)
	(visible waypoint0 waypoint36)
	(visible waypoint36 waypoint0)
	(visible waypoint1 waypoint13)
	(visible waypoint13 waypoint1)
	(visible waypoint1 waypoint17)
	(visible waypoint17 waypoint1)
	(visible waypoint1 waypoint18)
	(visible waypoint18 waypoint1)
	(visible waypoint1 waypoint20)
	(visible waypoint20 waypoint1)
	(visible waypoint2 waypoint0)
	(visible waypoint0 waypoint2)
	(visible waypoint2 waypoint12)
	(visible waypoint12 waypoint2)
	(visible waypoint2 waypoint14)
	(visible waypoint14 waypoint2)
	(visible waypoint2 waypoint15)
	(visible waypoint15 waypoint2)
	(visible waypoint2 waypoint23)
	(visible waypoint23 waypoint2)
	(visible waypoint2 waypoint32)
	(visible waypoint32 waypoint2)
	(visible waypoint2 waypoint35)
	(visible waypoint35 waypoint2)
	(visible waypoint2 waypoint38)
	(visible waypoint38 waypoint2)
	(visible waypoint3 waypoint5)
	(visible waypoint5 waypoint3)
	(visible waypoint3 waypoint9)
	(visible waypoint9 waypoint3)
	(visible waypoint3 waypoint12)
	(visible waypoint12 waypoint3)
	(visible waypoint3 waypoint14)
	(visible waypoint14 waypoint3)
	(visible waypoint3 waypoint15)
	(visible waypoint15 waypoint3)
	(visible waypoint3 waypoint32)
	(visible waypoint32 waypoint3)
	(visible waypoint3 waypoint34)
	(visible waypoint34 waypoint3)
	(visible waypoint4 waypoint15)
	(visible waypoint15 waypoint4)
	(visible waypoint5 waypoint1)
	(visible waypoint1 waypoint5)
	(visible waypoint5 waypoint6)
	(visible waypoint6 waypoint5)
	(visible waypoint5 waypoint15)
	(visible waypoint15 waypoint5)
	(visible waypoint5 waypoint23)
	(visible waypoint23 waypoint5)
	(visible waypoint5 waypoint34)
	(visible waypoint34 waypoint5)
	(visible waypoint5 waypoint35)
	(visible waypoint35 waypoint5)
	(visible waypoint5 waypoint39)
	(visible waypoint39 waypoint5)
	(visible waypoint6 waypoint17)
	(visible waypoint17 waypoint6)
	(visible waypoint6 waypoint29)
	(visible waypoint29 waypoint6)
	(visible waypoint7 waypoint13)
	(visible waypoint13 waypoint7)
	(visible waypoint7 waypoint15)
	(visible waypoint15 waypoint7)
	(visible waypoint7 waypoint16)
	(visible waypoint16 waypoint7)
	(visible waypoint7 waypoint18)
	(visible waypoint18 waypoint7)
	(visible waypoint7 waypoint30)
	(visible waypoint30 waypoint7)
	(visible waypoint7 waypoint31)
	(visible waypoint31 waypoint7)
	(visible waypoint7 waypoint36)
	(visible waypoint36 waypoint7)
	(visible waypoint8 waypoint4)
	(visible waypoint4 waypoint8)
	(visible waypoint8 waypoint27)
	(visible waypoint27 waypoint8)
	(visible waypoint8 waypoint31)
	(visible waypoint31 waypoint8)
	(visible waypoint8 waypoint33)
	(visible waypoint33 waypoint8)
	(visible waypoint9 waypoint2)
	(visible waypoint2 waypoint9)
	(visible waypoint9 waypoint11)
	(visible waypoint11 waypoint9)
	(visible waypoint9 waypoint30)
	(visible waypoint30 waypoint9)
	(visible waypoint10 waypoint16)
	(visible waypoint16 waypoint10)
	(visible waypoint10 waypoint17)
	(visible waypoint17 waypoint10)
	(visible waypoint10 waypoint19)
	(visible waypoint19 waypoint10)
	(visible waypoint10 waypoint25)
	(visible waypoint25 waypoint10)
	(visible waypoint10 waypoint39)
	(visible waypoint39 waypoint10)
	(visible waypoint11 waypoint0)
	(visible waypoint0 waypoint11)
	(visible waypoint11 waypoint19)
	(visible waypoint19 waypoint11)
	(visible waypoint11 waypoint24)
	(visible waypoint24 waypoint11)
	(visible waypoint11 waypoint33)
	(visible waypoint33 waypoint11)
	(visible waypoint12 waypoint9)
	(visible waypoint9 waypoint12)
	(visible waypoint12 waypoint27)
	(visible waypoint27 waypoint12)
	(visible waypoint12 waypoint29)
	(visible waypoint29 waypoint12)
	(visible waypoint12 waypoint33)
	(visible waypoint33 waypoint12)
	(visible waypoint13 waypoint29)
	(visible waypoint29 waypoint13)
	(visible waypoint13 waypoint39)
	(visible waypoint39 waypoint13)
	(visible waypoint14 waypoint1)
	(visible waypoint1 waypoint14)
	(visible waypoint14 waypoint7)
	(visible waypoint7 waypoint14)
	(visible waypoint14 waypoint18)
	(visible waypoint18 waypoint14)
	(visible waypoint14 waypoint23)
	(visible waypoint23 waypoint14)
	(visible waypoint14 waypoint37)
	(visible waypoint37 waypoint14)
	(visible waypoint15 waypoint9)
	(visible waypoint9 waypoint15)
	(visible waypoint15 waypoint25)
	(visible waypoint25 waypoint15)
	(visible waypoint15 waypoint27)
	(visible waypoint27 waypoint15)
	(visible waypoint16 waypoint17)
	(visible waypoint17 waypoint16)
	(visible waypoint16 waypoint26)
	(visible waypoint26 waypoint16)
	(visible waypoint16 waypoint29)
	(visible waypoint29 waypoint16)
	(visible waypoint16 waypoint30)
	(visible waypoint30 waypoint16)
	(visible waypoint17 waypoint3)
	(visible waypoint3 waypoint17)
	(visible waypoint17 waypoint18)
	(visible waypoint18 waypoint17)
	(visible waypoint17 waypoint23)
	(visible waypoint23 waypoint17)
	(visible waypoint17 waypoint32)
	(visible waypoint32 waypoint17)
	(visible waypoint18 waypoint5)
	(visible waypoint5 waypoint18)
	(visible waypoint18 waypoint6)
	(visible waypoint6 waypoint18)
	(visible waypoint18 waypoint8)
	(visible waypoint8 waypoint18)
	(visible waypoint18 waypoint9)
	(visible waypoint9 waypoint18)
	(visible waypoint18 waypoint11)
	(visible waypoint11 waypoint18)
	(visible waypoint18 waypoint20)
	(visible waypoint20 waypoint18)
	(visible waypoint19 waypoint13)
	(visible waypoint13 waypoint19)
	(visible waypoint19 waypoint30)
	(visible waypoint30 waypoint19)
	(visible waypoint19 waypoint32)
	(visible waypoint32 waypoint19)
	(visible waypoint20 waypoint6)
	(visible waypoint6 waypoint20)
	(visible waypoint20 waypoint8)
	(visible waypoint8 waypoint20)
	(visible waypoint20 waypoint10)
	(visible waypoint10 waypoint20)
	(visible waypoint20 waypoint15)
	(visible waypoint15 waypoint20)
	(visible waypoint20 waypoint23)
	(visible waypoint23 waypoint20)
	(visible waypoint20 waypoint34)
	(visible waypoint34 waypoint20)
	(visible waypoint21 waypoint3)
	(visible waypoint3 waypoint21)
	(visible waypoint21 waypoint22)
	(visible waypoint22 waypoint21)
	(visible waypoint21 waypoint26)
	(visible waypoint26 waypoint21)
	(visible waypoint21 waypoint28)
	(visible waypoint28 waypoint21)
	(visible waypoint22 waypoint3)
	(visible waypoint3 waypoint22)
	(visible waypoint22 waypoint7)
	(visible waypoint7 waypoint22)
	(visible waypoint22 waypoint15)
	(visible waypoint15 waypoint22)
	(visible waypoint22 waypoint35)
	(visible waypoint35 waypoint22)
	(visible waypoint23 waypoint1)
	(visible waypoint1 waypoint23)
	(visible waypoint23 waypoint10)
	(visible waypoint10 waypoint23)
	(visible waypoint23 waypoint21)
	(visible waypoint21 waypoint23)
	(visible waypoint23 waypoint24)
	(visible waypoint24 waypoint23)
	(visible waypoint23 waypoint36)
	(visible waypoint36 waypoint23)
	(visible waypoint23 waypoint38)
	(visible waypoint38 waypoint23)
	(visible waypoint24 waypoint2)
	(visible waypoint2 waypoint24)
	(visible waypoint24 waypoint12)
	(visible waypoint12 waypoint24)
	(visible waypoint24 waypoint16)
	(visible waypoint16 waypoint24)
	(visible waypoint24 waypoint35)
	(visible waypoint35 waypoint24)
	(visible waypoint25 waypoint14)
	(visible waypoint14 waypoint25)
	(visible waypoint25 waypoint16)
	(visible waypoint16 waypoint25)
	(visible waypoint25 waypoint20)
	(visible waypoint20 waypoint25)
	(visible waypoint25 waypoint34)
	(visible waypoint34 waypoint25)
	(visible waypoint26 waypoint3)
	(visible waypoint3 waypoint26)
	(visible waypoint26 waypoint9)
	(visible waypoint9 waypoint26)
	(visible waypoint26 waypoint12)
	(visible waypoint12 waypoint26)
	(visible waypoint26 waypoint19)
	(visible waypoint19 waypoint26)
	(visible waypoint26 waypoint31)
	(visible waypoint31 waypoint26)
	(visible waypoint27 waypoint2)
	(visible waypoint2 waypoint27)
	(visible waypoint27 waypoint4)
	(visible waypoint4 waypoint27)
	(visible waypoint27 waypoint13)
	(visible waypoint13 waypoint27)
	(visible waypoint27 waypoint22)
	(visible waypoint22 waypoint27)
	(visible waypoint27 waypoint31)
	(visible waypoint31 waypoint27)
	(visible waypoint27 waypoint33)
	(visible waypoint33 waypoint27)
	(visible waypoint28 waypoint4)
	(visible waypoint4 waypoint28)
	(visible waypoint28 waypoint14)
	(visible waypoint14 waypoint28)
	(visible waypoint28 waypoint15)
	(visible waypoint15 waypoint28)
	(visible waypoint29 waypoint17)
	(visible waypoint17 waypoint29)
	(visible waypoint29 waypoint23)
	(visible waypoint23 waypoint29)
	(visible waypoint29 waypoint25)
	(visible waypoint25 waypoint29)
	(visible waypoint29 waypoint39)
	(visible waypoint39 waypoint29)
	(visible waypoint30 waypoint0)
	(visible waypoint0 waypoint30)
	(visible waypoint30 waypoint5)
	(visible waypoint5 waypoint30)
	(visible waypoint31 waypoint3)
	(visible waypoint3 waypoint31)
	(visible waypoint31 waypoint4)
	(visible waypoint4 waypoint31)
	(visible waypoint31 waypoint9)
	(visible waypoint9 waypoint31)
	(visible waypoint31 waypoint15)
	(visible waypoint15 waypoint31)
	(visible waypoint31 waypoint37)
	(visible waypoint37 waypoint31)
	(visible waypoint32 waypoint9)
	(visible waypoint9 waypoint32)
	(visible waypoint32 waypoint12)
	(visible waypoint12 waypoint32)
	(visible waypoint32 waypoint14)
	(visible waypoint14 waypoint32)
	(visible waypoint32 waypoint22)
	(visible waypoint22 waypoint32)
	(visible waypoint33 waypoint1)
	(visible waypoint1 waypoint33)
	(visible waypoint33 waypoint2)
	(visible waypoint2 waypoint33)
	(visible waypoint33 waypoint19)
	(visible waypoint19 waypoint33)
	(visible waypoint33 waypoint30)
	(visible waypoint30 waypoint33)
	(visible waypoint33 waypoint32)
	(visible waypoint32 waypoint33)
	(visible waypoint34 waypoint11)
	(visible waypoint11 waypoint34)
	(visible waypoint34 waypoint14)
	(visible waypoint14 waypoint34)
	(visible waypoint34 waypoint18)
	(visible waypoint18 waypoint34)
	(visible waypoint34 waypoint28)
	(visible waypoint28 waypoint34)
	(visible waypoint34 waypoint32)
	(visible waypoint32 waypoint34)
	(visible waypoint34 waypoint37)
	(visible waypoint37 waypoint34)
	(visible waypoint35 waypoint6)
	(visible waypoint6 waypoint35)
	(visible waypoint35 waypoint16)
	(visible waypoint16 waypoint35)
	(visible waypoint35 waypoint27)
	(visible waypoint27 waypoint35)
	(visible waypoint35 waypoint31)
	(visible waypoint31 waypoint35)
	(visible waypoint36 waypoint3)
	(visible waypoint3 waypoint36)
	(visible waypoint36 waypoint5)
	(visible waypoint5 waypoint36)
	(visible waypoint36 waypoint9)
	(visible waypoint9 waypoint36)
	(visible waypoint36 waypoint24)
	(visible waypoint24 waypoint36)
	(visible waypoint37 waypoint6)
	(visible waypoint6 waypoint37)
	(visible waypoint37 waypoint24)
	(visible waypoint24 waypoint37)
	(visible waypoint37 waypoint26)
	(visible waypoint26 waypoint37)
	(visible waypoint37 waypoint35)
	(visible waypoint35 waypoint37)
	(visible waypoint38 waypoint33)
	(visible waypoint33 waypoint38)
	(visible waypoint38 waypoint34)
	(visible waypoint34 waypoint38)
	(visible waypoint38 waypoint37)
	(visible waypoint37 waypoint38)
	(visible waypoint39 waypoint24)
	(visible waypoint24 waypoint39)
	(visible waypoint39 waypoint25)
	(visible waypoint25 waypoint39)
	(visible waypoint39 waypoint32)
	(visible waypoint32 waypoint39)
	(visible waypoint39 waypoint34)
	(visible waypoint34 waypoint39)
	(at_soil_sample waypoint1)
	(at_soil_sample waypoint2)
	(at_rock_sample waypoint2)
	(at_rock_sample waypoint3)
	(at_soil_sample waypoint4)
	(at_rock_sample waypoint4)
	(at_soil_sample waypoint5)
	(at_rock_sample waypoint5)
	(at_soil_sample waypoint6)
	(at_rock_sample waypoint8)
	(at_soil_sample waypoint9)
	(at_rock_sample waypoint9)
	(at_soil_sample waypoint10)
	(at_rock_sample waypoint10)
	(at_soil_sample waypoint11)
	(at_soil_sample waypoint12)
	(at_soil_sample waypoint14)
	(at_rock_sample waypoint15)
	(at_rock_sample waypoint17)
	(at_soil_sample waypoint18)
	(at_rock_sample waypoint18)
	(at_rock_sample waypoint20)
	(at_soil_sample waypoint21)
	(at_rock_sample waypoint21)
	(at_soil_sample waypoint22)
	(at_soil_sample waypoint23)
	(at_rock_sample waypoint23)
	(at_soil_sample waypoint24)
	(at_soil_sample waypoint25)
	(at_rock_sample waypoint25)
	(at_soil_sample waypoint26)
	(at_rock_sample waypoint26)
	(at_soil_sample waypoint27)
	(at_rock_sample waypoint27)
	(at_rock_sample waypoint29)
	(at_rock_sample waypoint31)
	(at_soil_sample waypoint33)
	(at_soil_sample waypoint34)
	(at_soil_sample waypoint35)
	(at_rock_sample waypoint36)
	(at_soil_sample waypoint38)
	(at_rock_sample waypoint38)
	(at_soil_sample waypoint39)
	(at_lander general waypoint35)
	(channel_free general)
	(at rover0 waypoint28)
	(available rover0)
	(store_of rover0store rover0)
	(empty rover0store)
	(equipped_for_soil_analysis rover0)
	(equipped_for_rock_analysis rover0)
	(equipped_for_imaging rover0)
	(can_traverse rover0 waypoint28 waypoint4)
	(can_traverse rover0 waypoint4 waypoint28)
	(can_traverse rover0 waypoint28 waypoint14)
	(can_traverse rover0 waypoint14 waypoint28)
	(can_traverse rover0 waypoint28 waypoint21)
	(can_traverse rover0 waypoint21 waypoint28)
	(can_traverse rover0 waypoint28 waypoint34)
	(can_traverse rover0 waypoint34 waypoint28)
	(can_traverse rover0 waypoint4 waypoint0)
	(can_traverse rover0 waypoint0 waypoint4)
	(can_traverse rover0 waypoint4 waypoint8)
	(can_traverse rover0 waypoint8 waypoint4)
	(can_traverse rover0 waypoint4 waypoint15)
	(can_traverse rover0 waypoint15 waypoint4)
	(can_traverse rover0 waypoint4 waypoint27)
	(can_traverse rover0 waypoint27 waypoint4)
	(can_traverse rover0 waypoint4 waypoint31)
	(can_traverse rover0 waypoint31 waypoint4)
	(can_traverse rover0 waypoint14 waypoint2)
	(can_traverse rover0 waypoint2 waypoint14)
	(can_traverse rover0 waypoint14 waypoint23)
	(can_traverse rover0 waypoint23 waypoint14)
	(can_traverse rover0 waypoint14 waypoint25)
	(can_traverse rover0 waypoint25 waypoint14)
	(can_traverse rover0 waypoint14 waypoint32)
	(can_traverse rover0 waypoint32 waypoint14)
	(can_traverse rover0 waypoint14 waypoint37)
	(can_traverse rover0 waypoint37 waypoint14)
	(can_traverse rover0 waypoint21 waypoint3)
	(can_traverse rover0 waypoint3 waypoint21)
	(can_traverse rover0 waypoint21 waypoint22)
	(can_traverse rover0 waypoint22 waypoint21)
	(can_traverse rover0 waypoint21 waypoint26)
	(can_traverse rover0 waypoint26 waypoint21)
	(can_traverse rover0 waypoint34 waypoint11)
	(can_traverse rover0 waypoint11 waypoint34)
	(can_traverse rover0 waypoint34 waypoint18)
	(can_traverse rover0 waypoint18 waypoint34)
	(can_traverse rover0 waypoint34 waypoint38)
	(can_traverse rover0 waypoint38 waypoint34)
	(can_traverse rover0 waypoint0 waypoint30)
	(can_traverse rover0 waypoint30 waypoint0)
	(can_traverse rover0 waypoint0 waypoint36)
	(can_traverse rover0 waypoint36 waypoint0)
	(can_traverse rover0 waypoint8 waypoint20)
	(can_traverse rover0 waypoint20 waypoint8)
	(can_traverse rover0 waypoint8 waypoint33)
	(can_traverse rover0 waypoint33 waypoint8)
	(can_traverse rover0 waypoint15 waypoint5)
	(can_traverse rover0 waypoint5 waypoint15)
	(can_traverse rover0 waypoint15 waypoint9)
	(can_traverse rover0 waypoint9 waypoint15)
	(can_traverse rover0 waypoint27 waypoint12)
	(can_traverse rover0 waypoint12 waypoint27)
	(can_traverse rover0 waypoint27 waypoint13)
	(can_traverse rover0 waypoint13 waypoint27)
	(can_traverse rover0 waypoint27 waypoint35)
	(can_traverse rover0 waypoint35 waypoint27)
	(can_traverse rover0 waypoint2 waypoint24)
	(can_traverse rover0 waypoint24 waypoint2)
	(can_traverse rover0 waypoint23 waypoint17)
	(can_traverse rover0 waypoint17 waypoint23)
	(can_traverse rover0 waypoint23 waypoint29)
	(can_traverse rover0 waypoint29 waypoint23)
	(can_traverse rover0 waypoint25 waypoint10)
	(can_traverse rover0 waypoint10 waypoint25)
	(can_traverse rover0 waypoint32 waypoint39)
	(can_traverse rover0 waypoint39 waypoint32)
	(can_traverse rover0 waypoint37 waypoint6)
	(can_traverse rover0 waypoint6 waypoint37)
	(can_traverse rover0 waypoint22 waypoint7)
	(can_traverse rover0 waypoint7 waypoint22)
	(can_traverse rover0 waypoint26 waypoint19)
	(can_traverse rover0 waypoint19 waypoint26)
	(can_traverse rover0 waypoint18 waypoint1)
	(can_traverse rover0 waypoint1 waypoint18)
	(can_traverse rover0 waypoint24 waypoint16)
	(can_traverse rover0 waypoint16 waypoint24)
	(at rover1 waypoint36)
	(available rover1)
	(store_of rover1store rover1)
	(empty rover1store)
	(equipped_for_soil_analysis rover1)
	(equipped_for_rock_analysis rover1)
	(equipped_for_imaging rover1)
	(can_traverse rover1 waypoint36 waypoint0)
	(can_traverse rover1 waypoint0 waypoint36)
	(can_traverse rover1 waypoint36 waypoint3)
	(can_traverse rover1 waypoint3 waypoint36)
	(can_traverse rover1 waypoint36 waypoint5)
	(can_traverse rover1 waypoint5 waypoint36)
	(can_traverse rover1 waypoint36 waypoint9)
	(can_traverse rover1 waypoint9 waypoint36)
	(can_traverse rover1 waypoint0 waypoint4)
	(can_traverse rover1 waypoint4 waypoint0)
	(can_traverse rover1 waypoint0 waypoint11)
	(can_traverse rover1 waypoint11 waypoint0)
	(can_traverse rover1 waypoint0 waypoint27)
	(can_traverse rover1 waypoint27 waypoint0)
	(can_traverse rover1 waypoint0 waypoint30)
	(can_traverse rover1 waypoint30 waypoint0)
	(can_traverse rover1 waypoint3 waypoint14)
	(can_traverse rover1 waypoint14 waypoint3)
	(can_traverse rover1 waypoint3 waypoint17)
	(can_traverse rover1 waypoint17 waypoint3)
	(can_traverse rover1 waypoint3 waypoint21)
	(can_traverse rover1 waypoint21 waypoint3)
	(can_traverse rover1 waypoint3 waypoint26)
	(can_traverse rover1 waypoint26 waypoint3)
	(can_traverse rover1 waypoint3 waypoint31)
	(can_traverse rover1 waypoint31 waypoint3)
	(can_traverse rover1 waypoint3 waypoint32)
	(can_traverse rover1 waypoint32 waypoint3)
	(can_traverse rover1 waypoint3 waypoint34)
	(can_traverse rover1 waypoint34 waypoint3)
	(can_traverse rover1 waypoint5 waypoint1)
	(can_traverse rover1 waypoint1 waypoint5)
	(can_traverse rover1 waypoint5 waypoint15)
	(can_traverse rover1 waypoint15 waypoint5)
	(can_traverse rover1 waypoint5 waypoint18)
	(can_traverse rover1 waypoint18 waypoint5)
	(can_traverse rover1 waypoint5 waypoint23)
	(can_traverse rover1 waypoint23 waypoint5)
	(can_traverse rover1 waypoint5 waypoint35)
	(can_traverse rover1 waypoint35 waypoint5)
	(can_traverse rover1 waypoint5 waypoint39)
	(can_traverse rover1 waypoint39 waypoint5)
	(can_traverse rover1 waypoint9 waypoint12)
	(can_traverse rover1 waypoint12 waypoint9)
	(can_traverse rover1 waypoint4 waypoint8)
	(can_traverse rover1 waypoint8 waypoint4)
	(can_traverse rover1 waypoint4 waypoint28)
	(can_traverse rover1 waypoint28 waypoint4)
	(can_traverse rover1 waypoint11 waypoint19)
	(can_traverse rover1 waypoint19 waypoint11)
	(can_traverse rover1 waypoint11 waypoint33)
	(can_traverse rover1 waypoint33 waypoint11)
	(can_traverse rover1 waypoint27 waypoint2)
	(can_traverse rover1 waypoint2 waypoint27)
	(can_traverse rover1 waypoint27 waypoint22)
	(can_traverse rover1 waypoint22 waypoint27)
	(can_traverse rover1 waypoint30 waypoint16)
	(can_traverse rover1 waypoint16 waypoint30)
	(can_traverse rover1 waypoint14 waypoint7)
	(can_traverse rover1 waypoint7 waypoint14)
	(can_traverse rover1 waypoint14 waypoint25)
	(can_traverse rover1 waypoint25 waypoint14)
	(can_traverse rover1 waypoint14 waypoint37)
	(can_traverse rover1 waypoint37 waypoint14)
	(can_traverse rover1 waypoint17 waypoint6)
	(can_traverse rover1 waypoint6 waypoint17)
	(can_traverse rover1 waypoint17 waypoint10)
	(can_traverse rover1 waypoint10 waypoint17)
	(can_traverse rover1 waypoint34 waypoint20)
	(can_traverse rover1 waypoint20 waypoint34)
	(can_traverse rover1 waypoint34 waypoint38)
	(can_traverse rover1 waypoint38 waypoint34)
	(can_traverse rover1 waypoint1 waypoint13)
	(can_traverse rover1 waypoint13 waypoint1)
	(can_traverse rover1 waypoint23 waypoint24)
	(can_traverse rover1 waypoint24 waypoint23)
	(can_traverse rover1 waypoint23 waypoint29)
	(can_traverse rover1 waypoint29 waypoint23)
	(at rover2 waypoint29)
	(available rover2)
	(store_of rover2store rover2)
	(empty rover2store)
	(equipped_for_imaging rover2)
	(can_traverse rover2 waypoint29 waypoint6)
	(can_traverse rover2 waypoint6 waypoint29)
	(can_traverse rover2 waypoint29 waypoint12)
	(can_traverse rover2 waypoint12 waypoint29)
	(can_traverse rover2 waypoint29 waypoint13)
	(can_traverse rover2 waypoint13 waypoint29)
	(can_traverse rover2 waypoint29 waypoint17)
	(can_traverse rover2 waypoint17 waypoint29)
	(can_traverse rover2 waypoint29 waypoint25)
	(can_traverse rover2 waypoint25 waypoint29)
	(can_traverse rover2 waypoint29 waypoint39)
	(can_traverse rover2 waypoint39 waypoint29)
	(can_traverse rover2 waypoint6 waypoint5)
	(can_traverse rover2 waypoint5 waypoint6)
	(can_traverse rover2 waypoint6 waypoint18)
	(can_traverse rover2 waypoint18 waypoint6)
	(can_traverse rover2 waypoint6 waypoint35)
	(can_traverse rover2 waypoint35 waypoint6)
	(can_traverse rover2 waypoint6 waypoint37)
	(can_traverse rover2 waypoint37 waypoint6)
	(can_traverse rover2 waypoint12 waypoint2)
	(can_traverse rover2 waypoint2 waypoint12)
	(can_traverse rover2 waypoint12 waypoint3)
	(can_traverse rover2 waypoint3 waypoint12)
	(can_traverse rover2 waypoint12 waypoint9)
	(can_traverse rover2 waypoint9 waypoint12)
	(can_traverse rover2 waypoint12 waypoint24)
	(can_traverse rover2 waypoint24 waypoint12)
	(can_traverse rover2 waypoint12 waypoint26)
	(can_traverse rover2 waypoint26 waypoint12)
	(can_traverse rover2 waypoint13 waypoint7)
	(can_traverse rover2 waypoint7 waypoint13)
	(can_traverse rover2 waypoint13 waypoint19)
	(can_traverse rover2 waypoint19 waypoint13)
	(can_traverse rover2 waypoint17 waypoint1)
	(can_traverse rover2 waypoint1 waypoint17)
	(can_traverse rover2 waypoint17 waypoint16)
	(can_traverse rover2 waypoint16 waypoint17)
	(can_traverse rover2 waypoint17 waypoint32)
	(can_traverse rover2 waypoint32 waypoint17)
	(can_traverse rover2 waypoint25 waypoint10)
	(can_traverse rover2 waypoint10 waypoint25)
	(can_traverse rover2 waypoint25 waypoint14)
	(can_traverse rover2 waypoint14 waypoint25)
	(can_traverse rover2 waypoint25 waypoint15)
	(can_traverse rover2 waypoint15 waypoint25)
	(can_traverse rover2 waypoint25 waypoint34)
	(can_traverse rover2 waypoint34 waypoint25)
	(can_traverse rover2 waypoint5 waypoint23)
	(can_traverse rover2 waypoint23 waypoint5)
	(can_traverse rover2 waypoint5 waypoint36)
	(can_traverse rover2 waypoint36 waypoint5)
	(can_traverse rover2 waypoint18 waypoint8)
	(can_traverse rover2 waypoint8 waypoint18)
	(can_traverse rover2 waypoint18 waypoint20)
	(can_traverse rover2 waypoint20 waypoint18)
	(can_traverse rover2 waypoint35 waypoint22)
	(can_traverse rover2 waypoint22 waypoint35)
	(can_traverse rover2 waypoint35 waypoint27)
	(can_traverse rover2 waypoint27 waypoint35)
	(can_traverse rover2 waypoint35 waypoint31)
	(can_traverse rover2 waypoint31 waypoint35)
	(can_traverse rover2 waypoint2 waypoint0)
	(can_traverse rover2 waypoint0 waypoint2)
	(can_traverse rover2 waypoint2 waypoint38)
	(can_traverse rover2 waypoint38 waypoint2)
	(can_traverse rover2 waypoint9 waypoint30)
	(can_traverse rover2 waypoint30 waypoint9)
	(can_traverse rover2 waypoint26 waypoint21)
	(can_traverse rover2 waypoint21 waypoint26)
	(can_traverse rover2 waypoint19 waypoint11)
	(can_traverse rover2 waypoint11 waypoint19)
	(can_traverse rover2 waypoint1 waypoint33)
	(can_traverse rover2 waypoint33 waypoint1)
	(can_traverse rover2 waypoint15 waypoint4)
	(can_traverse rover2 waypoint4 waypoint15)
	(can_traverse rover2 waypoint15 waypoint28)
	(can_traverse rover2 waypoint28 waypoint15)
	(at rover3 waypoint18)
	(available rover3)
	(store_of rover3store rover3)
	(empty rover3store)
	(equipped_for_soil_analysis rover3)
	(equipped_for_imaging rover3)
	(can_traverse rover3 waypoint18 waypoint1)
	(can_traverse rover3 waypoint1 waypoint18)
	(can_traverse rover3 waypoint18 waypoint5)
	(can_traverse rover3 waypoint5 waypoint18)
	(can_traverse rover3 waypoint18 waypoint6)
	(can_traverse rover3 waypoint6 waypoint18)
	(can_traverse rover3 waypoint18 waypoint7)
	(can_traverse rover3 waypoint7 waypoint18)
	(can_traverse rover3 waypoint18 waypoint9)
	(can_traverse rover3 waypoint9 waypoint18)
	(can_traverse rover3 waypoint18 waypoint14)
	(can_traverse rover3 waypoint14 waypoint18)
	(can_traverse rover3 waypoint18 waypoint20)
	(can_traverse rover3 waypoint20 waypoint18)
	(can_traverse rover3 waypoint1 waypoint13)
	(can_traverse rover3 waypoint13 waypoint1)
	(can_traverse rover3 waypoint1 waypoint17)
	(can_traverse rover3 waypoint17 waypoint1)
	(can_traverse rover3 waypoint1 waypoint23)
	(can_traverse rover3 waypoint23 waypoint1)
	(can_traverse rover3 waypoint1 waypoint33)
	(can_traverse rover3 waypoint33 waypoint1)
	(can_traverse rover3 waypoint5 waypoint3)
	(can_traverse rover3 waypoint3 waypoint5)
	(can_traverse rover3 waypoint5 waypoint15)
	(can_traverse rover3 waypoint15 waypoint5)
	(can_traverse rover3 waypoint5 waypoint34)
	(can_traverse rover3 waypoint34 waypoint5)
	(can_traverse rover3 waypoint5 waypoint36)
	(can_traverse rover3 waypoint36 waypoint5)
	(can_traverse rover3 waypoint5 waypoint39)
	(can_traverse rover3 waypoint39 waypoint5)
	(can_traverse rover3 waypoint6 waypoint29)
	(can_traverse rover3 waypoint29 waypoint6)
	(can_traverse rover3 waypoint6 waypoint37)
	(can_traverse rover3 waypoint37 waypoint6)
	(can_traverse rover3 waypoint7 waypoint16)
	(can_traverse rover3 waypoint16 waypoint7)
	(can_traverse rover3 waypoint7 waypoint22)
	(can_traverse rover3 waypoint22 waypoint7)
	(can_traverse rover3 waypoint7 waypoint30)
	(can_traverse rover3 waypoint30 waypoint7)
	(can_traverse rover3 waypoint9 waypoint2)
	(can_traverse rover3 waypoint2 waypoint9)
	(can_traverse rover3 waypoint9 waypoint12)
	(can_traverse rover3 waypoint12 waypoint9)
	(can_traverse rover3 waypoint9 waypoint31)
	(can_traverse rover3 waypoint31 waypoint9)
	(can_traverse rover3 waypoint9 waypoint32)
	(can_traverse rover3 waypoint32 waypoint9)
	(can_traverse rover3 waypoint14 waypoint25)
	(can_traverse rover3 waypoint25 waypoint14)
	(can_traverse rover3 waypoint14 waypoint28)
	(can_traverse rover3 waypoint28 waypoint14)
	(can_traverse rover3 waypoint20 waypoint8)
	(can_traverse rover3 waypoint8 waypoint20)
	(can_traverse rover3 waypoint20 waypoint10)
	(can_traverse rover3 waypoint10 waypoint20)
	(can_traverse rover3 waypoint13 waypoint19)
	(can_traverse rover3 waypoint19 waypoint13)
	(can_traverse rover3 waypoint13 waypoint27)
	(can_traverse rover3 waypoint27 waypoint13)
	(can_traverse rover3 waypoint23 waypoint24)
	(can_traverse rover3 waypoint24 waypoint23)
	(can_traverse rover3 waypoint23 waypoint38)
	(can_traverse rover3 waypoint38 waypoint23)
	(can_traverse rover3 waypoint33 waypoint11)
	(can_traverse rover3 waypoint11 waypoint33)
	(can_traverse rover3 waypoint3 waypoint0)
	(can_traverse rover3 waypoint0 waypoint3)
	(can_traverse rover3 waypoint3 waypoint26)
	(can_traverse rover3 waypoint26 waypoint3)
	(can_traverse rover3 waypoint15 waypoint4)
	(can_traverse rover3 waypoint4 waypoint15)
	(at rover4 waypoint29)
	(available rover4)
	(store_of rover4store rover4)
	(empty rover4store)
	(equipped_for_soil_analysis rover4)
	(equipped_for_imaging rover4)
	(can_traverse rover4 waypoint29 waypoint6)
	(can_traverse rover4 waypoint6 waypoint29)
	(can_traverse rover4 waypoint29 waypoint12)
	(can_traverse rover4 waypoint12 waypoint29)
	(can_traverse rover4 waypoint29 waypoint13)
	(can_traverse rover4 waypoint13 waypoint29)
	(can_traverse rover4 waypoint29 waypoint17)
	(can_traverse rover4 waypoint17 waypoint29)
	(can_traverse rover4 waypoint29 waypoint23)
	(can_traverse rover4 waypoint23 waypoint29)
	(can_traverse rover4 waypoint29 waypoint25)
	(can_traverse rover4 waypoint25 waypoint29)
	(can_traverse rover4 waypoint29 waypoint39)
	(can_traverse rover4 waypoint39 waypoint29)
	(can_traverse rover4 waypoint6 waypoint5)
	(can_traverse rover4 waypoint5 waypoint6)
	(can_traverse rover4 waypoint6 waypoint18)
	(can_traverse rover4 waypoint18 waypoint6)
	(can_traverse rover4 waypoint6 waypoint35)
	(can_traverse rover4 waypoint35 waypoint6)
	(can_traverse rover4 waypoint12 waypoint2)
	(can_traverse rover4 waypoint2 waypoint12)
	(can_traverse rover4 waypoint12 waypoint9)
	(can_traverse rover4 waypoint9 waypoint12)
	(can_traverse rover4 waypoint12 waypoint24)
	(can_traverse rover4 waypoint24 waypoint12)
	(can_traverse rover4 waypoint12 waypoint26)
	(can_traverse rover4 waypoint26 waypoint12)
	(can_traverse rover4 waypoint12 waypoint27)
	(can_traverse rover4 waypoint27 waypoint12)
	(can_traverse rover4 waypoint12 waypoint32)
	(can_traverse rover4 waypoint32 waypoint12)
	(can_traverse rover4 waypoint12 waypoint33)
	(can_traverse rover4 waypoint33 waypoint12)
	(can_traverse rover4 waypoint13 waypoint7)
	(can_traverse rover4 waypoint7 waypoint13)
	(can_traverse rover4 waypoint13 waypoint19)
	(can_traverse rover4 waypoint19 waypoint13)
	(can_traverse rover4 waypoint17 waypoint1)
	(can_traverse rover4 waypoint1 waypoint17)
	(can_traverse rover4 waypoint17 waypoint3)
	(can_traverse rover4 waypoint3 waypoint17)
	(can_traverse rover4 waypoint23 waypoint14)
	(can_traverse rover4 waypoint14 waypoint23)
	(can_traverse rover4 waypoint23 waypoint21)
	(can_traverse rover4 waypoint21 waypoint23)
	(can_traverse rover4 waypoint23 waypoint36)
	(can_traverse rover4 waypoint36 waypoint23)
	(can_traverse rover4 waypoint23 waypoint38)
	(can_traverse rover4 waypoint38 waypoint23)
	(can_traverse rover4 waypoint25 waypoint10)
	(can_traverse rover4 waypoint10 waypoint25)
	(can_traverse rover4 waypoint25 waypoint15)
	(can_traverse rover4 waypoint15 waypoint25)
	(can_traverse rover4 waypoint39 waypoint34)
	(can_traverse rover4 waypoint34 waypoint39)
	(can_traverse rover4 waypoint5 waypoint30)
	(can_traverse rover4 waypoint30 waypoint5)
	(can_traverse rover4 waypoint18 waypoint20)
	(can_traverse rover4 waypoint20 waypoint18)
	(can_traverse rover4 waypoint35 waypoint16)
	(can_traverse rover4 waypoint16 waypoint35)
	(can_traverse rover4 waypoint35 waypoint31)
	(can_traverse rover4 waypoint31 waypoint35)
	(can_traverse rover4 waypoint24 waypoint11)
	(can_traverse rover4 waypoint11 waypoint24)
	(can_traverse rover4 waypoint24 waypoint37)
	(can_traverse rover4 waypoint37 waypoint24)
	(at rover5 waypoint14)
	(available rover5)
	(store_of rover5store rover5)
	(empty rover5store)
	(equipped_for_soil_analysis rover5)
	(equipped_for_rock_analysis rover5)
	(equipped_for_imaging rover5)
	(can_traverse rover5 waypoint14 waypoint1)
	(can_traverse rover5 waypoint1 waypoint14)
	(can_traverse rover5 waypoint14 waypoint3)
	(can_traverse rover5 waypoint3 waypoint14)
	(can_traverse rover5 waypoint14 waypoint7)
	(can_traverse rover5 waypoint7 waypoint14)
	(can_traverse rover5 waypoint14 waypoint25)
	(can_traverse rover5 waypoint25 waypoint14)
	(can_traverse rover5 waypoint14 waypoint32)
	(can_traverse rover5 waypoint32 waypoint14)
	(can_traverse rover5 waypoint14 waypoint37)
	(can_traverse rover5 waypoint37 waypoint14)
	(can_traverse rover5 waypoint1 waypoint17)
	(can_traverse rover5 waypoint17 waypoint1)
	(can_traverse rover5 waypoint1 waypoint18)
	(can_traverse rover5 waypoint18 waypoint1)
	(can_traverse rover5 waypoint1 waypoint20)
	(can_traverse rover5 waypoint20 waypoint1)
	(can_traverse rover5 waypoint1 waypoint23)
	(can_traverse rover5 waypoint23 waypoint1)
	(can_traverse rover5 waypoint3 waypoint0)
	(can_traverse rover5 waypoint0 waypoint3)
	(can_traverse rover5 waypoint3 waypoint9)
	(can_traverse rover5 waypoint9 waypoint3)
	(can_traverse rover5 waypoint3 waypoint15)
	(can_traverse rover5 waypoint15 waypoint3)
	(can_traverse rover5 waypoint3 waypoint21)
	(can_traverse rover5 waypoint21 waypoint3)
	(can_traverse rover5 waypoint3 waypoint31)
	(can_traverse rover5 waypoint31 waypoint3)
	(can_traverse rover5 waypoint3 waypoint34)
	(can_traverse rover5 waypoint34 waypoint3)
	(can_traverse rover5 waypoint7 waypoint13)
	(can_traverse rover5 waypoint13 waypoint7)
	(can_traverse rover5 waypoint7 waypoint16)
	(can_traverse rover5 waypoint16 waypoint7)
	(can_traverse rover5 waypoint7 waypoint22)
	(can_traverse rover5 waypoint22 waypoint7)
	(can_traverse rover5 waypoint7 waypoint36)
	(can_traverse rover5 waypoint36 waypoint7)
	(can_traverse rover5 waypoint25 waypoint39)
	(can_traverse rover5 waypoint39 waypoint25)
	(can_traverse rover5 waypoint32 waypoint2)
	(can_traverse rover5 waypoint2 waypoint32)
	(can_traverse rover5 waypoint32 waypoint12)
	(can_traverse rover5 waypoint12 waypoint32)
	(can_traverse rover5 waypoint32 waypoint19)
	(can_traverse rover5 waypoint19 waypoint32)
	(can_traverse rover5 waypoint32 waypoint33)
	(can_traverse rover5 waypoint33 waypoint32)
	(can_traverse rover5 waypoint37 waypoint6)
	(can_traverse rover5 waypoint6 waypoint37)
	(can_traverse rover5 waypoint37 waypoint24)
	(can_traverse rover5 waypoint24 waypoint37)
	(can_traverse rover5 waypoint37 waypoint26)
	(can_traverse rover5 waypoint26 waypoint37)
	(can_traverse rover5 waypoint37 waypoint35)
	(can_traverse rover5 waypoint35 waypoint37)
	(can_traverse rover5 waypoint37 waypoint38)
	(can_traverse rover5 waypoint38 waypoint37)
	(can_traverse rover5 waypoint17 waypoint10)
	(can_traverse rover5 waypoint10 waypoint17)
	(can_traverse rover5 waypoint17 waypoint29)
	(can_traverse rover5 waypoint29 waypoint17)
	(can_traverse rover5 waypoint18 waypoint5)
	(can_traverse rover5 waypoint5 waypoint18)
	(can_traverse rover5 waypoint18 waypoint8)
	(can_traverse rover5 waypoint8 waypoint18)
	(can_traverse rover5 waypoint0 waypoint4)
	(can_traverse rover5 waypoint4 waypoint0)
	(can_traverse rover5 waypoint0 waypoint11)
	(can_traverse rover5 waypoint11 waypoint0)
	(can_traverse rover5 waypoint0 waypoint27)
	(can_traverse rover5 waypoint27 waypoint0)
	(can_traverse rover5 waypoint9 waypoint30)
	(can_traverse rover5 waypoint30 waypoint9)
	(can_traverse rover5 waypoint15 waypoint28)
	(can_traverse rover5 waypoint28 waypoint15)
	(at rover6 waypoint4)
	(available rover6)
	(store_of rover6store rover6)
	(empty rover6store)
	(equipped_for_rock_analysis rover6)
	(can_traverse rover6 waypoint4 waypoint0)
	(can_traverse rover6 waypoint0 waypoint4)
	(can_traverse rover6 waypoint4 waypoint8)
	(can_traverse rover6 waypoint8 waypoint4)
	(can_traverse rover6 waypoint4 waypoint27)
	(can_traverse rover6 waypoint27 waypoint4)
	(can_traverse rover6 waypoint4 waypoint28)
	(can_traverse rover6 waypoint28 waypoint4)
	(can_traverse rover6 waypoint4 waypoint31)
	(can_traverse rover6 waypoint31 waypoint4)
	(can_traverse rover6 waypoint0 waypoint11)
	(can_traverse rover6 waypoint11 waypoint0)
	(can_traverse rover6 waypoint0 waypoint30)
	(can_traverse rover6 waypoint30 waypoint0)
	(can_traverse rover6 waypoint0 waypoint36)
	(can_traverse rover6 waypoint36 waypoint0)
	(can_traverse rover6 waypoint8 waypoint18)
	(can_traverse rover6 waypoint18 waypoint8)
	(can_traverse rover6 waypoint8 waypoint33)
	(can_traverse rover6 waypoint33 waypoint8)
	(can_traverse rover6 waypoint27 waypoint2)
	(can_traverse rover6 waypoint2 waypoint27)
	(can_traverse rover6 waypoint27 waypoint12)
	(can_traverse rover6 waypoint12 waypoint27)
	(can_traverse rover6 waypoint27 waypoint13)
	(can_traverse rover6 waypoint13 waypoint27)
	(can_traverse rover6 waypoint27 waypoint15)
	(can_traverse rover6 waypoint15 waypoint27)
	(can_traverse rover6 waypoint28 waypoint21)
	(can_traverse rover6 waypoint21 waypoint28)
	(can_traverse rover6 waypoint28 waypoint34)
	(can_traverse rover6 waypoint34 waypoint28)
	(can_traverse rover6 waypoint31 waypoint3)
	(can_traverse rover6 waypoint3 waypoint31)
	(can_traverse rover6 waypoint31 waypoint9)
	(can_traverse rover6 waypoint9 waypoint31)
	(can_traverse rover6 waypoint31 waypoint26)
	(can_traverse rover6 waypoint26 waypoint31)
	(can_traverse rover6 waypoint30 waypoint5)
	(can_traverse rover6 waypoint5 waypoint30)
	(can_traverse rover6 waypoint30 waypoint7)
	(can_traverse rover6 waypoint7 waypoint30)
	(can_traverse rover6 waypoint30 waypoint16)
	(can_traverse rover6 waypoint16 waypoint30)
	(can_traverse rover6 waypoint36 waypoint24)
	(can_traverse rover6 waypoint24 waypoint36)
	(can_traverse rover6 waypoint18 waypoint1)
	(can_traverse rover6 waypoint1 waypoint18)
	(can_traverse rover6 waypoint18 waypoint6)
	(can_traverse rover6 waypoint6 waypoint18)
	(can_traverse rover6 waypoint18 waypoint14)
	(can_traverse rover6 waypoint14 waypoint18)
	(can_traverse rover6 waypoint18 waypoint20)
	(can_traverse rover6 waypoint20 waypoint18)
	(can_traverse rover6 waypoint33 waypoint19)
	(can_traverse rover6 waypoint19 waypoint33)
	(can_traverse rover6 waypoint33 waypoint32)
	(can_traverse rover6 waypoint32 waypoint33)
	(can_traverse rover6 waypoint2 waypoint23)
	(can_traverse rover6 waypoint23 waypoint2)
	(can_traverse rover6 waypoint2 waypoint35)
	(can_traverse rover6 waypoint35 waypoint2)
	(can_traverse rover6 waypoint2 waypoint38)
	(can_traverse rover6 waypoint38 waypoint2)
	(can_traverse rover6 waypoint15 waypoint22)
	(can_traverse rover6 waypoint22 waypoint15)
	(can_traverse rover6 waypoint15 waypoint25)
	(can_traverse rover6 waypoint25 waypoint15)
	(at rover7 waypoint17)
	(available rover7)
	(store_of rover7store rover7)
	(empty rover7store)
	(equipped_for_soil_analysis rover7)
	(equipped_for_rock_analysis rover7)
	(equipped_for_imaging rover7)
	(can_traverse rover7 waypoint17 waypoint1)
	(can_traverse rover7 waypoint1 waypoint17)
	(can_traverse rover7 waypoint17 waypoint6)
	(can_traverse rover7 waypoint6 waypoint17)
	(can_traverse rover7 waypoint17 waypoint10)
	(can_traverse rover7 waypoint10 waypoint17)
	(can_traverse rover7 waypoint17 waypoint16)
	(can_traverse rover7 waypoint16 waypoint17)
	(can_traverse rover7 waypoint17 waypoint18)
	(can_traverse rover7 waypoint18 waypoint17)
	(can_traverse rover7 waypoint1 waypoint5)
	(can_traverse rover7 waypoint5 waypoint1)
	(can_traverse rover7 waypoint1 waypoint13)
	(can_traverse rover7 waypoint13 waypoint1)
	(can_traverse rover7 waypoint1 waypoint14)
	(can_traverse rover7 waypoint14 waypoint1)
	(can_traverse rover7 waypoint1 waypoint20)
	(can_traverse rover7 waypoint20 waypoint1)
	(can_traverse rover7 waypoint1 waypoint23)
	(can_traverse rover7 waypoint23 waypoint1)
	(can_traverse rover7 waypoint1 waypoint33)
	(can_traverse rover7 waypoint33 waypoint1)
	(can_traverse rover7 waypoint6 waypoint37)
	(can_traverse rover7 waypoint37 waypoint6)
	(can_traverse rover7 waypoint10 waypoint19)
	(can_traverse rover7 waypoint19 waypoint10)
	(can_traverse rover7 waypoint10 waypoint25)
	(can_traverse rover7 waypoint25 waypoint10)
	(can_traverse rover7 waypoint10 waypoint39)
	(can_traverse rover7 waypoint39 waypoint10)
	(can_traverse rover7 waypoint16 waypoint7)
	(can_traverse rover7 waypoint7 waypoint16)
	(can_traverse rover7 waypoint16 waypoint24)
	(can_traverse rover7 waypoint24 waypoint16)
	(can_traverse rover7 waypoint16 waypoint26)
	(can_traverse rover7 waypoint26 waypoint16)
	(can_traverse rover7 waypoint16 waypoint29)
	(can_traverse rover7 waypoint29 waypoint16)
	(can_traverse rover7 waypoint16 waypoint35)
	(can_traverse rover7 waypoint35 waypoint16)
	(can_traverse rover7 waypoint18 waypoint8)
	(can_traverse rover7 waypoint8 waypoint18)
	(can_traverse rover7 waypoint18 waypoint11)
	(can_traverse rover7 waypoint11 waypoint18)
	(can_traverse rover7 waypoint5 waypoint3)
	(can_traverse rover7 waypoint3 waypoint5)
	(can_traverse rover7 waypoint5 waypoint30)
	(can_traverse rover7 waypoint30 waypoint5)
	(can_traverse rover7 waypoint5 waypoint34)
	(can_traverse rover7 waypoint34 waypoint5)
	(can_traverse rover7 waypoint5 waypoint36)
	(can_traverse rover7 waypoint36 waypoint5)
	(can_traverse rover7 waypoint13 waypoint27)
	(can_traverse rover7 waypoint27 waypoint13)
	(can_traverse rover7 waypoint14 waypoint2)
	(can_traverse rover7 waypoint2 waypoint14)
	(can_traverse rover7 waypoint14 waypoint28)
	(can_traverse rover7 waypoint28 waypoint14)
	(can_traverse rover7 waypoint14 waypoint32)
	(can_traverse rover7 waypoint32 waypoint14)
	(can_traverse rover7 waypoint20 waypoint15)
	(can_traverse rover7 waypoint15 waypoint20)
	(can_traverse rover7 waypoint23 waypoint21)
	(can_traverse rover7 waypoint21 waypoint23)
	(can_traverse rover7 waypoint23 waypoint38)
	(can_traverse rover7 waypoint38 waypoint23)
	(can_traverse rover7 waypoint37 waypoint31)
	(can_traverse rover7 waypoint31 waypoint37)
	(can_traverse rover7 waypoint7 waypoint22)
	(can_traverse rover7 waypoint22 waypoint7)
	(can_traverse rover7 waypoint24 waypoint12)
	(can_traverse rover7 waypoint12 waypoint24)
	(can_traverse rover7 waypoint26 waypoint9)
	(can_traverse rover7 waypoint9 waypoint26)
	(can_traverse rover7 waypoint8 waypoint4)
	(can_traverse rover7 waypoint4 waypoint8)
	(can_traverse rover7 waypoint11 waypoint0)
	(can_traverse rover7 waypoint0 waypoint11)
	(on_board camera0 rover3)
	(calibration_target camera0 objective7)
	(supports camera0 high_res)
	(supports camera0 low_res)
	(on_board camera1 rover2)
	(calibration_target camera1 objective3)
	(supports camera1 low_res)
	(on_board camera2 rover2)
	(calibration_target camera2 objective3)
	(supports camera2 colour)
	(supports camera2 low_res)
	(on_board camera3 rover1)
	(calibration_target camera3 objective6)
	(supports camera3 colour)
	(supports camera3 high_res)
	(on_board camera4 rover4)
	(calibration_target camera4 objective4)
	(supports camera4 high_res)
	(supports camera4 low_res)
	(on_board camera5 rover2)
	(calibration_target camera5 objective0)
	(supports camera5 high_res)
	(on_board camera6 rover1)
	(calibration_target camera6 objective9)
	(supports camera6 colour)
	(supports camera6 low_res)
	(on_board camera7 rover7)
	(calibration_target camera7 objective2)
	(supports camera7 high_res)
	(supports camera7 low_res)
	(on_board camera8 rover2)
	(calibration_target camera8 objective4)
	(supports camera8 high_res)
	(on_board camera9 rover5)
	(calibration_target camera9 objective8)
	(supports camera9 colour)
	(supports camera9 low_res)
	(on_board camera10 rover0)
	(calibration_target camera10 objective6)
	(supports camera10 low_res)
	(visible_from objective0 waypoint0)
	(visible_from objective0 waypoint1)
	(visible_from objective0 waypoint2)
	(visible_from objective0 waypoint3)
	(visible_from objective0 waypoint4)
	(visible_from objective0 waypoint5)
	(visible_from objective0 waypoint6)
	(visible_from objective0 waypoint7)
	(visible_from objective0 waypoint8)
	(visible_from objective0 waypoint9)
	(visible_from objective0 waypoint10)
	(visible_from objective0 waypoint11)
	(visible_from objective0 waypoint12)
	(visible_from objective0 waypoint13)
	(visible_from objective0 waypoint14)
	(visible_from objective0 waypoint15)
	(visible_from objective0 waypoint16)
	(visible_from objective0 waypoint17)
	(visible_from objective0 waypoint18)
	(visible_from objective0 waypoint19)
	(visible_from objective0 waypoint20)
	(visible_from objective0 waypoint21)
	(visible_from objective0 waypoint22)
	(visible_from objective0 waypoint23)
	(visible_from objective0 waypoint24)
	(visible_from objective0 waypoint25)
	(visible_from objective0 waypoint26)
	(visible_from objective1 waypoint0)
	(visible_from objective1 waypoint1)
	(visible_from objective1 waypoint2)
	(visible_from objective1 waypoint3)
	(visible_from objective2 waypoint0)
	(visible_from objective2 waypoint1)
	(visible_from objective2 waypoint2)
	(visible_from objective2 waypoint3)
	(visible_from objective2 waypoint4)
	(visible_from objective2 waypoint5)
	(visible_from objective2 waypoint6)
	(visible_from objective2 waypoint7)
	(visible_from objective2 waypoint8)
	(visible_from objective2 waypoint9)
	(visible_from objective2 waypoint10)
	(visible_from objective2 waypoint11)
	(visible_from objective2 waypoint12)
	(visible_from objective2 waypoint13)
	(visible_from objective2 waypoint14)
	(visible_from objective2 waypoint15)
	(visible_from objective2 waypoint16)
	(visible_from objective2 waypoint17)
	(visible_from objective2 waypoint18)
	(visible_from objective2 waypoint19)
	(visible_from objective2 waypoint20)
	(visible_from objective2 waypoint21)
	(visible_from objective2 waypoint22)
	(visible_from objective2 waypoint23)
	(visible_from objective2 waypoint24)
	(visible_from objective3 waypoint0)
	(visible_from objective3 waypoint1)
	(visible_from objective3 waypoint2)
	(visible_from objective3 waypoint3)
	(visible_from objective3 waypoint4)
	(visible_from objective3 waypoint5)
	(visible_from objective3 waypoint6)
	(visible_from objective4 waypoint0)
	(visible_from objective4 waypoint1)
	(visible_from objective4 waypoint2)
	(visible_from objective4 waypoint3)
	(visible_from objective4 waypoint4)
	(visible_from objective4 waypoint5)
	(visible_from objective4 waypoint6)
	(visible_from objective4 waypoint7)
	(visible_from objective5 waypoint0)
	(visible_from objective5 waypoint1)
	(visible_from objective5 waypoint2)
	(visible_from objective5 waypoint3)
	(visible_from objective5 waypoint4)
	(visible_from objective5 waypoint5)
	(visible_from objective5 waypoint6)
	(visible_from objective5 waypoint7)
	(visible_from objective5 waypoint8)
	(visible_from objective5 waypoint9)
	(visible_from objective5 waypoint10)
	(visible_from objective5 waypoint11)
	(visible_from objective5 waypoint12)
	(visible_from objective5 waypoint13)
	(visible_from objective5 waypoint14)
	(visible_from objective5 waypoint15)
	(visible_from objective5 waypoint16)
	(visible_from objective5 waypoint17)
	(visible_from objective5 waypoint18)
	(visible_from objective6 waypoint0)
	(visible_from objective6 waypoint1)
	(visible_from objective6 waypoint2)
	(visible_from objective6 waypoint3)
	(visible_from objective6 waypoint4)
	(visible_from objective6 waypoint5)
	(visible_from objective6 waypoint6)
	(visible_from objective6 waypoint7)
	(visible_from objective6 waypoint8)
	(visible_from objective6 waypoint9)
	(visible_from objective6 waypoint10)
	(visible_from objective6 waypoint11)
	(visible_from objective6 waypoint12)
	(visible_from objective6 waypoint13)
	(visible_from objective6 waypoint14)
	(visible_from objective6 waypoint15)
	(visible_from objective6 waypoint16)
	(visible_from objective6 waypoint17)
	(visible_from objective6 waypoint18)
	(visible_from objective6 waypoint19)
	(visible_from objective6 waypoint20)
	(visible_from objective6 waypoint21)
	(visible_from objective6 waypoint22)
	(visible_from objective6 waypoint23)
	(visible_from objective6 waypoint24)
	(visible_from objective6 waypoint25)
	(visible_from objective6 waypoint26)
	(visible_from objective6 waypoint27)
	(visible_from objective7 waypoint0)
	(visible_from objective7 waypoint1)
	(visible_from objective7 waypoint2)
	(visible_from objective7 waypoint3)
	(visible_from objective7 waypoint4)
	(visible_from objective8 waypoint0)
	(visible_from objective8 waypoint1)
	(visible_from objective8 waypoint2)
	(visible_from objective8 waypoint3)
	(visible_from objective8 waypoint4)
	(visible_from objective8 waypoint5)
	(visible_from objective8 waypoint6)
	(visible_from objective8 waypoint7)
	(visible_from objective8 waypoint8)
	(visible_from objective8 waypoint9)
	(visible_from objective8 waypoint10)
	(visible_from objective8 waypoint11)
	(visible_from objective8 waypoint12)
	(visible_from objective8 waypoint13)
	(visible_from objective8 waypoint14)
	(visible_from objective8 waypoint15)
	(visible_from objective8 waypoint16)
	(visible_from objective8 waypoint17)
	(visible_from objective8 waypoint18)
	(visible_from objective8 waypoint19)
	(visible_from objective8 waypoint20)
	(visible_from objective8 waypoint21)
	(visible_from objective8 waypoint22)
	(visible_from objective8 waypoint23)
	(visible_from objective8 waypoint24)
	(visible_from objective8 waypoint25)
	(visible_from objective9 waypoint0)
	(visible_from objective9 waypoint1)
	(visible_from objective9 waypoint2)
	(visible_from objective9 waypoint3)
	(visible_from objective9 waypoint4)
	(visible_from objective9 waypoint5)
	(visible_from objective9 waypoint6)
	(visible_from objective9 waypoint7)
	(visible_from objective9 waypoint8)
	(visible_from objective9 waypoint9)
	(visible_from objective9 waypoint10)
	(K-obj rover2 rover7store)
	(K-obj rover2 rover3store)
	(K-obj rover2 waypoint15)
	(K-obj rover2 rover4store)
	(K-obj rover2 high_res)
	(K-obj rover2 waypoint27)
	(K-obj rover2 waypoint18)
	(K-obj rover2 camera9)
	(K-obj rover2 low_res)
	(K-obj rover2 camera0)
	(K-obj rover2 waypoint17)
	(K-obj rover2 objective9)
	(K-obj rover2 objective8)
	(K-obj rover2 rover5store)
	(K-obj rover2 objective1)
	(K-obj rover2 objective0)
	(K-obj rover2 objective3)
	(K-obj rover2 objective2)
	(K-obj rover2 objective5)
	(K-obj rover2 objective4)
	(K-obj rover2 objective7)
	(K-obj rover2 objective6)
	(K-obj rover2 waypoint36)
	(K-obj rover2 waypoint37)
	(K-obj rover2 waypoint34)
	(K-obj rover2 waypoint35)
	(K-obj rover2 waypoint32)
	(K-obj rover2 waypoint33)
	(K-obj rover2 waypoint30)
	(K-obj rover2 waypoint31)
	(K-obj rover2 waypoint12)
	(K-obj rover2 waypoint38)
	(K-obj rover2 waypoint39)
	(K-obj rover2 camera3)
	(K-obj rover2 camera2)
	(K-obj rover2 rover0store)
	(K-obj rover2 general)
	(K-obj rover2 waypoint16)
	(K-obj rover2 waypoint11)
	(K-obj rover2 camera10)
	(K-obj rover2 rover6store)
	(K-obj rover2 waypoint25)
	(K-obj rover2 waypoint24)
	(K-obj rover2 rover2store)
	(K-obj rover2 waypoint26)
	(K-obj rover2 waypoint21)
	(K-obj rover2 waypoint20)
	(K-obj rover2 waypoint23)
	(K-obj rover2 waypoint22)
	(K-obj rover2 waypoint29)
	(K-obj rover2 waypoint28)
	(K-obj rover2 camera4)
	(K-obj rover2 waypoint8)
	(K-obj rover2 waypoint9)
	(K-obj rover2 waypoint6)
	(K-obj rover2 waypoint7)
	(K-obj rover2 waypoint4)
	(K-obj rover2 waypoint5)
	(K-obj rover2 waypoint2)
	(K-obj rover2 waypoint3)
	(K-obj rover2 waypoint0)
	(K-obj rover2 waypoint1)
	(K-obj rover2 camera8)
	(K-obj rover2 waypoint19)
	(K-obj rover2 waypoint10)
	(K-obj rover2 camera1)
	(K-obj rover2 colour)
	(K-obj rover2 waypoint13)
	(K-obj rover2 waypoint14)
	(K-obj rover2 camera5)
	(K-obj rover2 camera6)
	(K-obj rover2 camera7)
	(K-obj rover2 rover1store)
	(K-obj rover3 rover7store)
	(K-obj rover3 rover3store)
	(K-obj rover3 waypoint15)
	(K-obj rover3 rover4store)
	(K-obj rover3 high_res)
	(K-obj rover3 waypoint27)
	(K-obj rover3 waypoint18)
	(K-obj rover3 camera9)
	(K-obj rover3 low_res)
	(K-obj rover3 camera0)
	(K-obj rover3 waypoint17)
	(K-obj rover3 objective9)
	(K-obj rover3 objective8)
	(K-obj rover3 rover5store)
	(K-obj rover3 objective1)
	(K-obj rover3 objective0)
	(K-obj rover3 objective3)
	(K-obj rover3 objective2)
	(K-obj rover3 objective5)
	(K-obj rover3 objective4)
	(K-obj rover3 objective7)
	(K-obj rover3 objective6)
	(K-obj rover3 waypoint36)
	(K-obj rover3 waypoint37)
	(K-obj rover3 waypoint34)
	(K-obj rover3 waypoint35)
	(K-obj rover3 waypoint32)
	(K-obj rover3 waypoint33)
	(K-obj rover3 waypoint30)
	(K-obj rover3 waypoint31)
	(K-obj rover3 waypoint12)
	(K-obj rover3 waypoint38)
	(K-obj rover3 waypoint39)
	(K-obj rover3 camera3)
	(K-obj rover3 camera2)
	(K-obj rover3 rover0store)
	(K-obj rover3 general)
	(K-obj rover3 waypoint16)
	(K-obj rover3 waypoint11)
	(K-obj rover3 camera10)
	(K-obj rover3 rover6store)
	(K-obj rover3 waypoint25)
	(K-obj rover3 waypoint24)
	(K-obj rover3 rover2store)
	(K-obj rover3 waypoint26)
	(K-obj rover3 waypoint21)
	(K-obj rover3 waypoint20)
	(K-obj rover3 waypoint23)
	(K-obj rover3 waypoint22)
	(K-obj rover3 waypoint29)
	(K-obj rover3 waypoint28)
	(K-obj rover3 camera4)
	(K-obj rover3 waypoint8)
	(K-obj rover3 waypoint9)
	(K-obj rover3 waypoint6)
	(K-obj rover3 waypoint7)
	(K-obj rover3 waypoint4)
	(K-obj rover3 waypoint5)
	(K-obj rover3 waypoint2)
	(K-obj rover3 waypoint3)
	(K-obj rover3 waypoint0)
	(K-obj rover3 waypoint1)
	(K-obj rover3 camera8)
	(K-obj rover3 waypoint19)
	(K-obj rover3 waypoint10)
	(K-obj rover3 camera1)
	(K-obj rover3 colour)
	(K-obj rover3 waypoint13)
	(K-obj rover3 waypoint14)
	(K-obj rover3 camera5)
	(K-obj rover3 camera6)
	(K-obj rover3 camera7)
	(K-obj rover3 rover1store)
	(K-obj rover0 rover7store)
	(K-obj rover0 rover3store)
	(K-obj rover0 waypoint15)
	(K-obj rover0 rover4store)
	(K-obj rover0 high_res)
	(K-obj rover0 waypoint27)
	(K-obj rover0 waypoint18)
	(K-obj rover0 camera9)
	(K-obj rover0 low_res)
	(K-obj rover0 camera0)
	(K-obj rover0 waypoint17)
	(K-obj rover0 objective9)
	(K-obj rover0 objective8)
	(K-obj rover0 rover5store)
	(K-obj rover0 objective1)
	(K-obj rover0 objective0)
	(K-obj rover0 objective3)
	(K-obj rover0 objective2)
	(K-obj rover0 objective5)
	(K-obj rover0 objective4)
	(K-obj rover0 objective7)
	(K-obj rover0 objective6)
	(K-obj rover0 waypoint36)
	(K-obj rover0 waypoint37)
	(K-obj rover0 waypoint34)
	(K-obj rover0 waypoint35)
	(K-obj rover0 waypoint32)
	(K-obj rover0 waypoint33)
	(K-obj rover0 waypoint30)
	(K-obj rover0 waypoint31)
	(K-obj rover0 waypoint12)
	(K-obj rover0 waypoint38)
	(K-obj rover0 waypoint39)
	(K-obj rover0 camera3)
	(K-obj rover0 camera2)
	(K-obj rover0 rover0store)
	(K-obj rover0 general)
	(K-obj rover0 waypoint16)
	(K-obj rover0 waypoint11)
	(K-obj rover0 camera10)
	(K-obj rover0 rover6store)
	(K-obj rover0 waypoint25)
	(K-obj rover0 waypoint24)
	(K-obj rover0 rover2store)
	(K-obj rover0 waypoint26)
	(K-obj rover0 waypoint21)
	(K-obj rover0 waypoint20)
	(K-obj rover0 waypoint23)
	(K-obj rover0 waypoint22)
	(K-obj rover0 waypoint29)
	(K-obj rover0 waypoint28)
	(K-obj rover0 camera4)
	(K-obj rover0 waypoint8)
	(K-obj rover0 waypoint9)
	(K-obj rover0 waypoint6)
	(K-obj rover0 waypoint7)
	(K-obj rover0 waypoint4)
	(K-obj rover0 waypoint5)
	(K-obj rover0 waypoint2)
	(K-obj rover0 waypoint3)
	(K-obj rover0 waypoint0)
	(K-obj rover0 waypoint1)
	(K-obj rover0 camera8)
	(K-obj rover0 waypoint19)
	(K-obj rover0 waypoint10)
	(K-obj rover0 camera1)
	(K-obj rover0 colour)
	(K-obj rover0 waypoint13)
	(K-obj rover0 waypoint14)
	(K-obj rover0 camera5)
	(K-obj rover0 camera6)
	(K-obj rover0 camera7)
	(K-obj rover0 rover1store)
	(K-obj rover1 rover7store)
	(K-obj rover1 rover3store)
	(K-obj rover1 waypoint15)
	(K-obj rover1 rover4store)
	(K-obj rover1 high_res)
	(K-obj rover1 waypoint27)
	(K-obj rover1 waypoint18)
	(K-obj rover1 camera9)
	(K-obj rover1 low_res)
	(K-obj rover1 camera0)
	(K-obj rover1 waypoint17)
	(K-obj rover1 objective9)
	(K-obj rover1 objective8)
	(K-obj rover1 rover5store)
	(K-obj rover1 objective1)
	(K-obj rover1 objective0)
	(K-obj rover1 objective3)
	(K-obj rover1 objective2)
	(K-obj rover1 objective5)
	(K-obj rover1 objective4)
	(K-obj rover1 objective7)
	(K-obj rover1 objective6)
	(K-obj rover1 waypoint36)
	(K-obj rover1 waypoint37)
	(K-obj rover1 waypoint34)
	(K-obj rover1 waypoint35)
	(K-obj rover1 waypoint32)
	(K-obj rover1 waypoint33)
	(K-obj rover1 waypoint30)
	(K-obj rover1 waypoint31)
	(K-obj rover1 waypoint12)
	(K-obj rover1 waypoint38)
	(K-obj rover1 waypoint39)
	(K-obj rover1 camera3)
	(K-obj rover1 camera2)
	(K-obj rover1 rover0store)
	(K-obj rover1 general)
	(K-obj rover1 waypoint16)
	(K-obj rover1 waypoint11)
	(K-obj rover1 camera10)
	(K-obj rover1 rover6store)
	(K-obj rover1 waypoint25)
	(K-obj rover1 waypoint24)
	(K-obj rover1 rover2store)
	(K-obj rover1 waypoint26)
	(K-obj rover1 waypoint21)
	(K-obj rover1 waypoint20)
	(K-obj rover1 waypoint23)
	(K-obj rover1 waypoint22)
	(K-obj rover1 waypoint29)
	(K-obj rover1 waypoint28)
	(K-obj rover1 camera4)
	(K-obj rover1 waypoint8)
	(K-obj rover1 waypoint9)
	(K-obj rover1 waypoint6)
	(K-obj rover1 waypoint7)
	(K-obj rover1 waypoint4)
	(K-obj rover1 waypoint5)
	(K-obj rover1 waypoint2)
	(K-obj rover1 waypoint3)
	(K-obj rover1 waypoint0)
	(K-obj rover1 waypoint1)
	(K-obj rover1 camera8)
	(K-obj rover1 waypoint19)
	(K-obj rover1 waypoint10)
	(K-obj rover1 camera1)
	(K-obj rover1 colour)
	(K-obj rover1 waypoint13)
	(K-obj rover1 waypoint14)
	(K-obj rover1 camera5)
	(K-obj rover1 camera6)
	(K-obj rover1 camera7)
	(K-obj rover1 rover1store)
	(K-obj rover6 rover7store)
	(K-obj rover6 rover3store)
	(K-obj rover6 waypoint15)
	(K-obj rover6 rover4store)
	(K-obj rover6 high_res)
	(K-obj rover6 waypoint27)
	(K-obj rover6 waypoint18)
	(K-obj rover6 camera9)
	(K-obj rover6 low_res)
	(K-obj rover6 camera0)
	(K-obj rover6 waypoint17)
	(K-obj rover6 objective9)
	(K-obj rover6 objective8)
	(K-obj rover6 rover5store)
	(K-obj rover6 objective1)
	(K-obj rover6 objective0)
	(K-obj rover6 objective3)
	(K-obj rover6 objective2)
	(K-obj rover6 objective5)
	(K-obj rover6 objective4)
	(K-obj rover6 objective7)
	(K-obj rover6 objective6)
	(K-obj rover6 waypoint36)
	(K-obj rover6 waypoint37)
	(K-obj rover6 waypoint34)
	(K-obj rover6 waypoint35)
	(K-obj rover6 waypoint32)
	(K-obj rover6 waypoint33)
	(K-obj rover6 waypoint30)
	(K-obj rover6 waypoint31)
	(K-obj rover6 waypoint12)
	(K-obj rover6 waypoint38)
	(K-obj rover6 waypoint39)
	(K-obj rover6 camera3)
	(K-obj rover6 camera2)
	(K-obj rover6 rover0store)
	(K-obj rover6 general)
	(K-obj rover6 waypoint16)
	(K-obj rover6 waypoint11)
	(K-obj rover6 camera10)
	(K-obj rover6 rover6store)
	(K-obj rover6 waypoint25)
	(K-obj rover6 waypoint24)
	(K-obj rover6 rover2store)
	(K-obj rover6 waypoint26)
	(K-obj rover6 waypoint21)
	(K-obj rover6 waypoint20)
	(K-obj rover6 waypoint23)
	(K-obj rover6 waypoint22)
	(K-obj rover6 waypoint29)
	(K-obj rover6 waypoint28)
	(K-obj rover6 camera4)
	(K-obj rover6 waypoint8)
	(K-obj rover6 waypoint9)
	(K-obj rover6 waypoint6)
	(K-obj rover6 waypoint7)
	(K-obj rover6 waypoint4)
	(K-obj rover6 waypoint5)
	(K-obj rover6 waypoint2)
	(K-obj rover6 waypoint3)
	(K-obj rover6 waypoint0)
	(K-obj rover6 waypoint1)
	(K-obj rover6 camera8)
	(K-obj rover6 waypoint19)
	(K-obj rover6 waypoint10)
	(K-obj rover6 camera1)
	(K-obj rover6 colour)
	(K-obj rover6 waypoint13)
	(K-obj rover6 waypoint14)
	(K-obj rover6 camera5)
	(K-obj rover6 camera6)
	(K-obj rover6 camera7)
	(K-obj rover6 rover1store)
	(K-obj rover7 rover7store)
	(K-obj rover7 rover3store)
	(K-obj rover7 waypoint15)
	(K-obj rover7 rover4store)
	(K-obj rover7 high_res)
	(K-obj rover7 waypoint27)
	(K-obj rover7 waypoint18)
	(K-obj rover7 camera9)
	(K-obj rover7 low_res)
	(K-obj rover7 camera0)
	(K-obj rover7 waypoint17)
	(K-obj rover7 objective9)
	(K-obj rover7 objective8)
	(K-obj rover7 rover5store)
	(K-obj rover7 objective1)
	(K-obj rover7 objective0)
	(K-obj rover7 objective3)
	(K-obj rover7 objective2)
	(K-obj rover7 objective5)
	(K-obj rover7 objective4)
	(K-obj rover7 objective7)
	(K-obj rover7 objective6)
	(K-obj rover7 waypoint36)
	(K-obj rover7 waypoint37)
	(K-obj rover7 waypoint34)
	(K-obj rover7 waypoint35)
	(K-obj rover7 waypoint32)
	(K-obj rover7 waypoint33)
	(K-obj rover7 waypoint30)
	(K-obj rover7 waypoint31)
	(K-obj rover7 waypoint12)
	(K-obj rover7 waypoint38)
	(K-obj rover7 waypoint39)
	(K-obj rover7 camera3)
	(K-obj rover7 camera2)
	(K-obj rover7 rover0store)
	(K-obj rover7 general)
	(K-obj rover7 waypoint16)
	(K-obj rover7 waypoint11)
	(K-obj rover7 camera10)
	(K-obj rover7 rover6store)
	(K-obj rover7 waypoint25)
	(K-obj rover7 waypoint24)
	(K-obj rover7 rover2store)
	(K-obj rover7 waypoint26)
	(K-obj rover7 waypoint21)
	(K-obj rover7 waypoint20)
	(K-obj rover7 waypoint23)
	(K-obj rover7 waypoint22)
	(K-obj rover7 waypoint29)
	(K-obj rover7 waypoint28)
	(K-obj rover7 camera4)
	(K-obj rover7 waypoint8)
	(K-obj rover7 waypoint9)
	(K-obj rover7 waypoint6)
	(K-obj rover7 waypoint7)
	(K-obj rover7 waypoint4)
	(K-obj rover7 waypoint5)
	(K-obj rover7 waypoint2)
	(K-obj rover7 waypoint3)
	(K-obj rover7 waypoint0)
	(K-obj rover7 waypoint1)
	(K-obj rover7 camera8)
	(K-obj rover7 waypoint19)
	(K-obj rover7 waypoint10)
	(K-obj rover7 camera1)
	(K-obj rover7 colour)
	(K-obj rover7 waypoint13)
	(K-obj rover7 waypoint14)
	(K-obj rover7 camera5)
	(K-obj rover7 camera6)
	(K-obj rover7 camera7)
	(K-obj rover7 rover1store)
	(K-obj rover4 rover7store)
	(K-obj rover4 rover3store)
	(K-obj rover4 waypoint15)
	(K-obj rover4 rover4store)
	(K-obj rover4 high_res)
	(K-obj rover4 waypoint27)
	(K-obj rover4 waypoint18)
	(K-obj rover4 camera9)
	(K-obj rover4 low_res)
	(K-obj rover4 camera0)
	(K-obj rover4 waypoint17)
	(K-obj rover4 objective9)
	(K-obj rover4 objective8)
	(K-obj rover4 rover5store)
	(K-obj rover4 objective1)
	(K-obj rover4 objective0)
	(K-obj rover4 objective3)
	(K-obj rover4 objective2)
	(K-obj rover4 objective5)
	(K-obj rover4 objective4)
	(K-obj rover4 objective7)
	(K-obj rover4 objective6)
	(K-obj rover4 waypoint36)
	(K-obj rover4 waypoint37)
	(K-obj rover4 waypoint34)
	(K-obj rover4 waypoint35)
	(K-obj rover4 waypoint32)
	(K-obj rover4 waypoint33)
	(K-obj rover4 waypoint30)
	(K-obj rover4 waypoint31)
	(K-obj rover4 waypoint12)
	(K-obj rover4 waypoint38)
	(K-obj rover4 waypoint39)
	(K-obj rover4 camera3)
	(K-obj rover4 camera2)
	(K-obj rover4 rover0store)
	(K-obj rover4 general)
	(K-obj rover4 waypoint16)
	(K-obj rover4 waypoint11)
	(K-obj rover4 camera10)
	(K-obj rover4 rover6store)
	(K-obj rover4 waypoint25)
	(K-obj rover4 waypoint24)
	(K-obj rover4 rover2store)
	(K-obj rover4 waypoint26)
	(K-obj rover4 waypoint21)
	(K-obj rover4 waypoint20)
	(K-obj rover4 waypoint23)
	(K-obj rover4 waypoint22)
	(K-obj rover4 waypoint29)
	(K-obj rover4 waypoint28)
	(K-obj rover4 camera4)
	(K-obj rover4 waypoint8)
	(K-obj rover4 waypoint9)
	(K-obj rover4 waypoint6)
	(K-obj rover4 waypoint7)
	(K-obj rover4 waypoint4)
	(K-obj rover4 waypoint5)
	(K-obj rover4 waypoint2)
	(K-obj rover4 waypoint3)
	(K-obj rover4 waypoint0)
	(K-obj rover4 waypoint1)
	(K-obj rover4 camera8)
	(K-obj rover4 waypoint19)
	(K-obj rover4 waypoint10)
	(K-obj rover4 camera1)
	(K-obj rover4 colour)
	(K-obj rover4 waypoint13)
	(K-obj rover4 waypoint14)
	(K-obj rover4 camera5)
	(K-obj rover4 camera6)
	(K-obj rover4 camera7)
	(K-obj rover4 rover1store)
	(K-obj rover5 rover7store)
	(K-obj rover5 rover3store)
	(K-obj rover5 waypoint15)
	(K-obj rover5 rover4store)
	(K-obj rover5 high_res)
	(K-obj rover5 waypoint27)
	(K-obj rover5 waypoint18)
	(K-obj rover5 camera9)
	(K-obj rover5 low_res)
	(K-obj rover5 camera0)
	(K-obj rover5 waypoint17)
	(K-obj rover5 objective9)
	(K-obj rover5 objective8)
	(K-obj rover5 rover5store)
	(K-obj rover5 objective1)
	(K-obj rover5 objective0)
	(K-obj rover5 objective3)
	(K-obj rover5 objective2)
	(K-obj rover5 objective5)
	(K-obj rover5 objective4)
	(K-obj rover5 objective7)
	(K-obj rover5 objective6)
	(K-obj rover5 waypoint36)
	(K-obj rover5 waypoint37)
	(K-obj rover5 waypoint34)
	(K-obj rover5 waypoint35)
	(K-obj rover5 waypoint32)
	(K-obj rover5 waypoint33)
	(K-obj rover5 waypoint30)
	(K-obj rover5 waypoint31)
	(K-obj rover5 waypoint12)
	(K-obj rover5 waypoint38)
	(K-obj rover5 waypoint39)
	(K-obj rover5 camera3)
	(K-obj rover5 camera2)
	(K-obj rover5 rover0store)
	(K-obj rover5 general)
	(K-obj rover5 waypoint16)
	(K-obj rover5 waypoint11)
	(K-obj rover5 camera10)
	(K-obj rover5 rover6store)
	(K-obj rover5 waypoint25)
	(K-obj rover5 waypoint24)
	(K-obj rover5 rover2store)
	(K-obj rover5 waypoint26)
	(K-obj rover5 waypoint21)
	(K-obj rover5 waypoint20)
	(K-obj rover5 waypoint23)
	(K-obj rover5 waypoint22)
	(K-obj rover5 waypoint29)
	(K-obj rover5 waypoint28)
	(K-obj rover5 camera4)
	(K-obj rover5 waypoint8)
	(K-obj rover5 waypoint9)
	(K-obj rover5 waypoint6)
	(K-obj rover5 waypoint7)
	(K-obj rover5 waypoint4)
	(K-obj rover5 waypoint5)
	(K-obj rover5 waypoint2)
	(K-obj rover5 waypoint3)
	(K-obj rover5 waypoint0)
	(K-obj rover5 waypoint1)
	(K-obj rover5 camera8)
	(K-obj rover5 waypoint19)
	(K-obj rover5 waypoint10)
	(K-obj rover5 camera1)
	(K-obj rover5 colour)
	(K-obj rover5 waypoint13)
	(K-obj rover5 waypoint14)
	(K-obj rover5 camera5)
	(K-obj rover5 camera6)
	(K-obj rover5 camera7)
	(K-obj rover5 rover1store)
	(K-obj rover2 rover2)
	(K-obj rover3 rover3)
	(K-obj rover0 rover0)
	(K-obj rover1 rover1)
	(K-obj rover6 rover6)
	(K-obj rover7 rover7)
	(K-obj rover4 rover4)
	(K-obj rover5 rover5)
	(K-ag-pred rover2 pred--at)
	(K-ag-pred rover2 pred--can_traverse)
	(K-ag-pred rover2 pred--equipped_for_soil_analysis)
	(K-ag-pred rover2 pred--equipped_for_rock_analysis)
	(K-ag-pred rover2 pred--equipped_for_imaging)
	(K-ag-pred rover2 pred--have_rock_analysis)
	(K-ag-pred rover2 pred--have_soil_analysis)
	(K-ag-pred rover2 pred--calibrated)
	(K-ag-pred rover2 pred--available)
	(K-ag-pred rover2 pred--have_image)
	(K-ag-pred rover2 pred--store_of)
	(K-ag-pred rover2 pred--on_board)
	(K-ag-pred rover3 pred--at)
	(K-ag-pred rover3 pred--can_traverse)
	(K-ag-pred rover3 pred--equipped_for_soil_analysis)
	(K-ag-pred rover3 pred--equipped_for_rock_analysis)
	(K-ag-pred rover3 pred--equipped_for_imaging)
	(K-ag-pred rover3 pred--have_rock_analysis)
	(K-ag-pred rover3 pred--have_soil_analysis)
	(K-ag-pred rover3 pred--calibrated)
	(K-ag-pred rover3 pred--available)
	(K-ag-pred rover3 pred--have_image)
	(K-ag-pred rover3 pred--store_of)
	(K-ag-pred rover3 pred--on_board)
	(K-ag-pred rover0 pred--at)
	(K-ag-pred rover0 pred--can_traverse)
	(K-ag-pred rover0 pred--equipped_for_soil_analysis)
	(K-ag-pred rover0 pred--equipped_for_rock_analysis)
	(K-ag-pred rover0 pred--equipped_for_imaging)
	(K-ag-pred rover0 pred--have_rock_analysis)
	(K-ag-pred rover0 pred--have_soil_analysis)
	(K-ag-pred rover0 pred--calibrated)
	(K-ag-pred rover0 pred--available)
	(K-ag-pred rover0 pred--have_image)
	(K-ag-pred rover0 pred--store_of)
	(K-ag-pred rover0 pred--on_board)
	(K-ag-pred rover1 pred--at)
	(K-ag-pred rover1 pred--can_traverse)
	(K-ag-pred rover1 pred--equipped_for_soil_analysis)
	(K-ag-pred rover1 pred--equipped_for_rock_analysis)
	(K-ag-pred rover1 pred--equipped_for_imaging)
	(K-ag-pred rover1 pred--have_rock_analysis)
	(K-ag-pred rover1 pred--have_soil_analysis)
	(K-ag-pred rover1 pred--calibrated)
	(K-ag-pred rover1 pred--available)
	(K-ag-pred rover1 pred--have_image)
	(K-ag-pred rover1 pred--store_of)
	(K-ag-pred rover1 pred--on_board)
	(K-ag-pred rover6 pred--at)
	(K-ag-pred rover6 pred--can_traverse)
	(K-ag-pred rover6 pred--equipped_for_soil_analysis)
	(K-ag-pred rover6 pred--equipped_for_rock_analysis)
	(K-ag-pred rover6 pred--equipped_for_imaging)
	(K-ag-pred rover6 pred--have_rock_analysis)
	(K-ag-pred rover6 pred--have_soil_analysis)
	(K-ag-pred rover6 pred--calibrated)
	(K-ag-pred rover6 pred--available)
	(K-ag-pred rover6 pred--have_image)
	(K-ag-pred rover6 pred--store_of)
	(K-ag-pred rover6 pred--on_board)
	(K-ag-pred rover7 pred--at)
	(K-ag-pred rover7 pred--can_traverse)
	(K-ag-pred rover7 pred--equipped_for_soil_analysis)
	(K-ag-pred rover7 pred--equipped_for_rock_analysis)
	(K-ag-pred rover7 pred--equipped_for_imaging)
	(K-ag-pred rover7 pred--have_rock_analysis)
	(K-ag-pred rover7 pred--have_soil_analysis)
	(K-ag-pred rover7 pred--calibrated)
	(K-ag-pred rover7 pred--available)
	(K-ag-pred rover7 pred--have_image)
	(K-ag-pred rover7 pred--store_of)
	(K-ag-pred rover7 pred--on_board)
	(K-ag-pred rover4 pred--at)
	(K-ag-pred rover4 pred--can_traverse)
	(K-ag-pred rover4 pred--equipped_for_soil_analysis)
	(K-ag-pred rover4 pred--equipped_for_rock_analysis)
	(K-ag-pred rover4 pred--equipped_for_imaging)
	(K-ag-pred rover4 pred--have_rock_analysis)
	(K-ag-pred rover4 pred--have_soil_analysis)
	(K-ag-pred rover4 pred--calibrated)
	(K-ag-pred rover4 pred--available)
	(K-ag-pred rover4 pred--have_image)
	(K-ag-pred rover4 pred--store_of)
	(K-ag-pred rover4 pred--on_board)
	(K-ag-pred rover5 pred--at)
	(K-ag-pred rover5 pred--can_traverse)
	(K-ag-pred rover5 pred--equipped_for_soil_analysis)
	(K-ag-pred rover5 pred--equipped_for_rock_analysis)
	(K-ag-pred rover5 pred--equipped_for_imaging)
	(K-ag-pred rover5 pred--have_rock_analysis)
	(K-ag-pred rover5 pred--have_soil_analysis)
	(K-ag-pred rover5 pred--calibrated)
	(K-ag-pred rover5 pred--available)
	(K-ag-pred rover5 pred--have_image)
	(K-ag-pred rover5 pred--store_of)
	(K-ag-pred rover5 pred--on_board)
	(K-ag-pred rover2 pred--visible)
	(K-pred rover2 pred--visible)
	(K-ag-pred rover3 pred--visible)
	(K-pred rover3 pred--visible)
	(K-ag-pred rover0 pred--visible)
	(K-pred rover0 pred--visible)
	(K-ag-pred rover1 pred--visible)
	(K-pred rover1 pred--visible)
	(K-ag-pred rover6 pred--visible)
	(K-pred rover6 pred--visible)
	(K-ag-pred rover7 pred--visible)
	(K-pred rover7 pred--visible)
	(K-ag-pred rover4 pred--visible)
	(K-pred rover4 pred--visible)
	(K-ag-pred rover5 pred--visible)
	(K-pred rover5 pred--visible)
	(K-ag-pred rover2 pred--visible_from)
	(K-pred rover2 pred--visible_from)
	(K-ag-pred rover3 pred--visible_from)
	(K-pred rover3 pred--visible_from)
	(K-ag-pred rover0 pred--visible_from)
	(K-pred rover0 pred--visible_from)
	(K-ag-pred rover1 pred--visible_from)
	(K-pred rover1 pred--visible_from)
	(K-ag-pred rover6 pred--visible_from)
	(K-pred rover6 pred--visible_from)
	(K-ag-pred rover7 pred--visible_from)
	(K-pred rover7 pred--visible_from)
	(K-ag-pred rover4 pred--visible_from)
	(K-pred rover4 pred--visible_from)
	(K-ag-pred rover5 pred--visible_from)
	(K-pred rover5 pred--visible_from)
	(K-ag-pred rover2 pred--at_rock_sample)
	(K-pred rover2 pred--at_rock_sample)
	(K-ag-pred rover3 pred--at_rock_sample)
	(K-pred rover3 pred--at_rock_sample)
	(K-ag-pred rover0 pred--at_rock_sample)
	(K-pred rover0 pred--at_rock_sample)
	(K-ag-pred rover1 pred--at_rock_sample)
	(K-pred rover1 pred--at_rock_sample)
	(K-ag-pred rover6 pred--at_rock_sample)
	(K-pred rover6 pred--at_rock_sample)
	(K-ag-pred rover7 pred--at_rock_sample)
	(K-pred rover7 pred--at_rock_sample)
	(K-ag-pred rover4 pred--at_rock_sample)
	(K-pred rover4 pred--at_rock_sample)
	(K-ag-pred rover5 pred--at_rock_sample)
	(K-pred rover5 pred--at_rock_sample)
	(K-ag-pred rover2 pred--at_soil_sample)
	(K-pred rover2 pred--at_soil_sample)
	(K-ag-pred rover3 pred--at_soil_sample)
	(K-pred rover3 pred--at_soil_sample)
	(K-ag-pred rover0 pred--at_soil_sample)
	(K-pred rover0 pred--at_soil_sample)
	(K-ag-pred rover1 pred--at_soil_sample)
	(K-pred rover1 pred--at_soil_sample)
	(K-ag-pred rover6 pred--at_soil_sample)
	(K-pred rover6 pred--at_soil_sample)
	(K-ag-pred rover7 pred--at_soil_sample)
	(K-pred rover7 pred--at_soil_sample)
	(K-ag-pred rover4 pred--at_soil_sample)
	(K-pred rover4 pred--at_soil_sample)
	(K-ag-pred rover5 pred--at_soil_sample)
	(K-pred rover5 pred--at_soil_sample)
	(K-ag-pred rover2 pred--at_lander)
	(K-pred rover2 pred--at_lander)
	(K-ag-pred rover3 pred--at_lander)
	(K-pred rover3 pred--at_lander)
	(K-ag-pred rover0 pred--at_lander)
	(K-pred rover0 pred--at_lander)
	(K-ag-pred rover1 pred--at_lander)
	(K-pred rover1 pred--at_lander)
	(K-ag-pred rover6 pred--at_lander)
	(K-pred rover6 pred--at_lander)
	(K-ag-pred rover7 pred--at_lander)
	(K-pred rover7 pred--at_lander)
	(K-ag-pred rover4 pred--at_lander)
	(K-pred rover4 pred--at_lander)
	(K-ag-pred rover5 pred--at_lander)
	(K-pred rover5 pred--at_lander)
	(K-ag-pred rover2 pred--communicated_image_data)
	(K-pred rover2 pred--communicated_image_data)
	(K-ag-pred rover3 pred--communicated_image_data)
	(K-pred rover3 pred--communicated_image_data)
	(K-ag-pred rover0 pred--communicated_image_data)
	(K-pred rover0 pred--communicated_image_data)
	(K-ag-pred rover1 pred--communicated_image_data)
	(K-pred rover1 pred--communicated_image_data)
	(K-ag-pred rover6 pred--communicated_image_data)
	(K-pred rover6 pred--communicated_image_data)
	(K-ag-pred rover7 pred--communicated_image_data)
	(K-pred rover7 pred--communicated_image_data)
	(K-ag-pred rover4 pred--communicated_image_data)
	(K-pred rover4 pred--communicated_image_data)
	(K-ag-pred rover5 pred--communicated_image_data)
	(K-pred rover5 pred--communicated_image_data)
	(K-ag-pred rover2 pred--communicated_rock_data)
	(K-pred rover2 pred--communicated_rock_data)
	(K-ag-pred rover3 pred--communicated_rock_data)
	(K-pred rover3 pred--communicated_rock_data)
	(K-ag-pred rover0 pred--communicated_rock_data)
	(K-pred rover0 pred--communicated_rock_data)
	(K-ag-pred rover1 pred--communicated_rock_data)
	(K-pred rover1 pred--communicated_rock_data)
	(K-ag-pred rover6 pred--communicated_rock_data)
	(K-pred rover6 pred--communicated_rock_data)
	(K-ag-pred rover7 pred--communicated_rock_data)
	(K-pred rover7 pred--communicated_rock_data)
	(K-ag-pred rover4 pred--communicated_rock_data)
	(K-pred rover4 pred--communicated_rock_data)
	(K-ag-pred rover5 pred--communicated_rock_data)
	(K-pred rover5 pred--communicated_rock_data)
	(K-ag-pred rover2 pred--communicated_soil_data)
	(K-pred rover2 pred--communicated_soil_data)
	(K-ag-pred rover3 pred--communicated_soil_data)
	(K-pred rover3 pred--communicated_soil_data)
	(K-ag-pred rover0 pred--communicated_soil_data)
	(K-pred rover0 pred--communicated_soil_data)
	(K-ag-pred rover1 pred--communicated_soil_data)
	(K-pred rover1 pred--communicated_soil_data)
	(K-ag-pred rover6 pred--communicated_soil_data)
	(K-pred rover6 pred--communicated_soil_data)
	(K-ag-pred rover7 pred--communicated_soil_data)
	(K-pred rover7 pred--communicated_soil_data)
	(K-ag-pred rover4 pred--communicated_soil_data)
	(K-pred rover4 pred--communicated_soil_data)
	(K-ag-pred rover5 pred--communicated_soil_data)
	(K-pred rover5 pred--communicated_soil_data)
	(K-ag-pred rover2 pred--empty)
	(K-pred rover2 pred--empty)
	(K-ag-pred rover3 pred--empty)
	(K-pred rover3 pred--empty)
	(K-ag-pred rover0 pred--empty)
	(K-pred rover0 pred--empty)
	(K-ag-pred rover1 pred--empty)
	(K-pred rover1 pred--empty)
	(K-ag-pred rover6 pred--empty)
	(K-pred rover6 pred--empty)
	(K-ag-pred rover7 pred--empty)
	(K-pred rover7 pred--empty)
	(K-ag-pred rover4 pred--empty)
	(K-pred rover4 pred--empty)
	(K-ag-pred rover5 pred--empty)
	(K-pred rover5 pred--empty)
	(K-ag-pred rover2 pred--full)
	(K-pred rover2 pred--full)
	(K-ag-pred rover3 pred--full)
	(K-pred rover3 pred--full)
	(K-ag-pred rover0 pred--full)
	(K-pred rover0 pred--full)
	(K-ag-pred rover1 pred--full)
	(K-pred rover1 pred--full)
	(K-ag-pred rover6 pred--full)
	(K-pred rover6 pred--full)
	(K-ag-pred rover7 pred--full)
	(K-pred rover7 pred--full)
	(K-ag-pred rover4 pred--full)
	(K-pred rover4 pred--full)
	(K-ag-pred rover5 pred--full)
	(K-pred rover5 pred--full)
	(K-ag-pred rover2 pred--supports)
	(K-pred rover2 pred--supports)
	(K-ag-pred rover3 pred--supports)
	(K-pred rover3 pred--supports)
	(K-ag-pred rover0 pred--supports)
	(K-pred rover0 pred--supports)
	(K-ag-pred rover1 pred--supports)
	(K-pred rover1 pred--supports)
	(K-ag-pred rover6 pred--supports)
	(K-pred rover6 pred--supports)
	(K-ag-pred rover7 pred--supports)
	(K-pred rover7 pred--supports)
	(K-ag-pred rover4 pred--supports)
	(K-pred rover4 pred--supports)
	(K-ag-pred rover5 pred--supports)
	(K-pred rover5 pred--supports)
	(K-ag-pred rover2 pred--calibration_target)
	(K-pred rover2 pred--calibration_target)
	(K-ag-pred rover3 pred--calibration_target)
	(K-pred rover3 pred--calibration_target)
	(K-ag-pred rover0 pred--calibration_target)
	(K-pred rover0 pred--calibration_target)
	(K-ag-pred rover1 pred--calibration_target)
	(K-pred rover1 pred--calibration_target)
	(K-ag-pred rover6 pred--calibration_target)
	(K-pred rover6 pred--calibration_target)
	(K-ag-pred rover7 pred--calibration_target)
	(K-pred rover7 pred--calibration_target)
	(K-ag-pred rover4 pred--calibration_target)
	(K-pred rover4 pred--calibration_target)
	(K-ag-pred rover5 pred--calibration_target)
	(K-pred rover5 pred--calibration_target)
	(K-ag-pred rover2 pred--channel_free)
	(K-pred rover2 pred--channel_free)
	(K-ag-pred rover3 pred--channel_free)
	(K-pred rover3 pred--channel_free)
	(K-ag-pred rover0 pred--channel_free)
	(K-pred rover0 pred--channel_free)
	(K-ag-pred rover1 pred--channel_free)
	(K-pred rover1 pred--channel_free)
	(K-ag-pred rover6 pred--channel_free)
	(K-pred rover6 pred--channel_free)
	(K-ag-pred rover7 pred--channel_free)
	(K-pred rover7 pred--channel_free)
	(K-ag-pred rover4 pred--channel_free)
	(K-pred rover4 pred--channel_free)
	(K-ag-pred rover5 pred--channel_free)
	(K-pred rover5 pred--channel_free)
)
(:goal	(and
(communicated_soil_data waypoint21) (communicated_soil_data waypoint34) (communicated_soil_data waypoint26) (communicated_soil_data waypoint22) (communicated_soil_data waypoint27) (communicated_soil_data waypoint5) (communicated_soil_data waypoint9) (communicated_rock_data waypoint9) (communicated_rock_data waypoint27) (communicated_rock_data waypoint15) (communicated_rock_data waypoint20) (communicated_rock_data waypoint18) (communicated_rock_data waypoint2) (communicated_image_data objective2 colour) (communicated_image_data objective6 colour) (communicated_image_data objective8 colour) (communicated_image_data objective0 high_res) (communicated_image_data objective5 colour) (communicated_image_data objective0 colour))
)
(:metric minimize (total-time))
)

