(define (problem depotprob7512) (:domain depot)
(:objects
	truck1 - truck
	truck0 - truck
	depot0 - depot
	crate1 - crate
	crate0 - crate
	crate3 - crate
	crate2 - crate
	pallet1 - pallet
	pallet0 - pallet
	pallet2 - pallet
	distributor1 - distributor
	distributor0 - distributor
)
(:init
	(clear crate0)
	(clear crate3)
	(clear crate2)
	(on crate0 pallet0)
	(on crate1 pallet2)
	(on crate2 crate1)
	(on crate3 pallet1)
	(K-obj depot0 truck1)
	(K-obj depot0 truck0)
	(K-obj depot0 depot0)
	(K-obj depot0 crate1)
	(K-obj depot0 crate0)
	(K-obj depot0 crate3)
	(K-obj depot0 crate2)
	(K-obj depot0 pallet1)
	(K-obj depot0 pallet0)
	(K-obj depot0 pallet2)
	(K-obj depot0 distributor1)
	(K-obj depot0 distributor0)
	(K-obj distributor1 truck1)
	(K-obj distributor1 truck0)
	(K-obj distributor1 depot0)
	(K-obj distributor1 crate1)
	(K-obj distributor1 crate0)
	(K-obj distributor1 crate3)
	(K-obj distributor1 crate2)
	(K-obj distributor1 pallet1)
	(K-obj distributor1 pallet0)
	(K-obj distributor1 pallet2)
	(K-obj distributor1 distributor1)
	(K-obj distributor1 distributor0)
	(K-obj distributor0 truck1)
	(K-obj distributor0 truck0)
	(K-obj distributor0 depot0)
	(K-obj distributor0 crate1)
	(K-obj distributor0 crate0)
	(K-obj distributor0 crate3)
	(K-obj distributor0 crate2)
	(K-obj distributor0 pallet1)
	(K-obj distributor0 pallet0)
	(K-obj distributor0 pallet2)
	(K-obj distributor0 distributor1)
	(K-obj distributor0 distributor0)
	(K-ag-pred depot0 pred--lifting)
	(K-ag-pred depot0 pred--available)
	(K-ag-pred distributor1 pred--lifting)
	(K-ag-pred distributor1 pred--available)
	(K-ag-pred distributor0 pred--lifting)
	(K-ag-pred distributor0 pred--available)
	(K-ag-pred depot0 pred--at)
	(K-pred depot0 pred--at)
	(K-ag-pred distributor1 pred--at)
	(K-pred distributor1 pred--at)
	(K-ag-pred distributor0 pred--at)
	(K-pred distributor0 pred--at)
	(K-ag-pred depot0 pred--on)
	(K-pred depot0 pred--on)
	(K-ag-pred distributor1 pred--on)
	(K-pred distributor1 pred--on)
	(K-ag-pred distributor0 pred--on)
	(K-pred distributor0 pred--on)
	(K-ag-pred depot0 pred--in)
	(K-pred depot0 pred--in)
	(K-ag-pred distributor1 pred--in)
	(K-pred distributor1 pred--in)
	(K-ag-pred distributor0 pred--in)
	(K-pred distributor0 pred--in)
	(K-ag-pred depot0 pred--clear)
	(K-pred depot0 pred--clear)
	(K-ag-pred distributor1 pred--clear)
	(K-pred distributor1 pred--clear)
	(K-ag-pred distributor0 pred--clear)
	(K-pred distributor0 pred--clear)
)
(:goal	(and
<HYPOTHESIS>
)
)
(:metric minimize (total-time))
)