(define (problem roverprob3965) (:domain rover)
(:objects
objective2 - objective
rover7store - store
rover3store - store
rover0store - store
colour - mode
general - lander
waypoint15 - waypoint
waypoint16 - waypoint
rover4store - store
waypoint11 - waypoint
rover9store - store
waypoint10 - waypoint
high_res - mode
waypoint27 - waypoint
rover6store - store
waypoint25 - waypoint
waypoint24 - waypoint
rover2store - store
waypoint26 - waypoint
waypoint21 - waypoint
waypoint20 - waypoint
waypoint23 - waypoint
waypoint22 - waypoint
waypoint29 - waypoint
waypoint28 - waypoint
camera4 - camera
waypoint8 - waypoint
waypoint9 - waypoint
waypoint6 - waypoint
waypoint7 - waypoint
low_res - mode
waypoint5 - waypoint
waypoint2 - waypoint
waypoint3 - waypoint
waypoint0 - waypoint
waypoint1 - waypoint
waypoint4 - waypoint
rover8 - rover
rover9 - rover
objective3 - objective
waypoint13 - waypoint
rover2 - rover
rover3 - rover
rover0 - rover
rover1 - rover
rover6 - rover
rover7 - rover
rover4 - rover
rover5 - rover
waypoint18 - waypoint
waypoint19 - waypoint
camera5 - camera
rover5store - store
objective1 - objective
camera1 - camera
camera2 - camera
camera3 - camera
objective5 - objective
objective4 - objective
camera6 - camera
waypoint17 - waypoint
camera0 - camera
rover8store - store
waypoint14 - waypoint
objective0 - objective
rover1store - store
waypoint12 - waypoint
)
(:init (= (total-cost) 0) (considered_occur_init)
(visible waypoint0 waypoint11)
(visible waypoint11 waypoint0)
(visible waypoint0 waypoint29)
(visible waypoint29 waypoint0)
(visible waypoint1 waypoint0)
(visible waypoint0 waypoint1)
(visible waypoint1 waypoint4)
(visible waypoint4 waypoint1)
(visible waypoint1 waypoint6)
(visible waypoint6 waypoint1)
(visible waypoint1 waypoint15)
(visible waypoint15 waypoint1)
(visible waypoint1 waypoint25)
(visible waypoint25 waypoint1)
(visible waypoint2 waypoint9)
(visible waypoint9 waypoint2)
(visible waypoint2 waypoint16)
(visible waypoint16 waypoint2)
(visible waypoint2 waypoint24)
(visible waypoint24 waypoint2)
(visible waypoint3 waypoint10)
(visible waypoint10 waypoint3)
(visible waypoint3 waypoint13)
(visible waypoint13 waypoint3)
(visible waypoint3 waypoint26)
(visible waypoint26 waypoint3)
(visible waypoint3 waypoint27)
(visible waypoint27 waypoint3)
(visible waypoint4 waypoint6)
(visible waypoint6 waypoint4)
(visible waypoint4 waypoint9)
(visible waypoint9 waypoint4)
(visible waypoint4 waypoint10)
(visible waypoint10 waypoint4)
(visible waypoint5 waypoint1)
(visible waypoint1 waypoint5)
(visible waypoint5 waypoint6)
(visible waypoint6 waypoint5)
(visible waypoint5 waypoint11)
(visible waypoint11 waypoint5)
(visible waypoint5 waypoint14)
(visible waypoint14 waypoint5)
(visible waypoint5 waypoint19)
(visible waypoint19 waypoint5)
(visible waypoint5 waypoint23)
(visible waypoint23 waypoint5)
(visible waypoint6 waypoint11)
(visible waypoint11 waypoint6)
(visible waypoint6 waypoint19)
(visible waypoint19 waypoint6)
(visible waypoint6 waypoint22)
(visible waypoint22 waypoint6)
(visible waypoint7 waypoint5)
(visible waypoint5 waypoint7)
(visible waypoint7 waypoint6)
(visible waypoint6 waypoint7)
(visible waypoint7 waypoint14)
(visible waypoint14 waypoint7)
(visible waypoint7 waypoint20)
(visible waypoint20 waypoint7)
(visible waypoint7 waypoint21)
(visible waypoint21 waypoint7)
(visible waypoint7 waypoint23)
(visible waypoint23 waypoint7)
(visible waypoint7 waypoint27)
(visible waypoint27 waypoint7)
(visible waypoint8 waypoint0)
(visible waypoint0 waypoint8)
(visible waypoint8 waypoint2)
(visible waypoint2 waypoint8)
(visible waypoint8 waypoint14)
(visible waypoint14 waypoint8)
(visible waypoint8 waypoint15)
(visible waypoint15 waypoint8)
(visible waypoint8 waypoint25)
(visible waypoint25 waypoint8)
(visible waypoint8 waypoint27)
(visible waypoint27 waypoint8)
(visible waypoint9 waypoint10)
(visible waypoint10 waypoint9)
(visible waypoint9 waypoint24)
(visible waypoint24 waypoint9)
(visible waypoint10 waypoint8)
(visible waypoint8 waypoint10)
(visible waypoint10 waypoint15)
(visible waypoint15 waypoint10)
(visible waypoint10 waypoint20)
(visible waypoint20 waypoint10)
(visible waypoint10 waypoint21)
(visible waypoint21 waypoint10)
(visible waypoint10 waypoint23)
(visible waypoint23 waypoint10)
(visible waypoint11 waypoint16)
(visible waypoint16 waypoint11)
(visible waypoint11 waypoint18)
(visible waypoint18 waypoint11)
(visible waypoint12 waypoint1)
(visible waypoint1 waypoint12)
(visible waypoint12 waypoint4)
(visible waypoint4 waypoint12)
(visible waypoint12 waypoint6)
(visible waypoint6 waypoint12)
(visible waypoint12 waypoint9)
(visible waypoint9 waypoint12)
(visible waypoint12 waypoint16)
(visible waypoint16 waypoint12)
(visible waypoint12 waypoint23)
(visible waypoint23 waypoint12)
(visible waypoint13 waypoint5)
(visible waypoint5 waypoint13)
(visible waypoint13 waypoint20)
(visible waypoint20 waypoint13)
(visible waypoint14 waypoint6)
(visible waypoint6 waypoint14)
(visible waypoint14 waypoint10)
(visible waypoint10 waypoint14)
(visible waypoint14 waypoint21)
(visible waypoint21 waypoint14)
(visible waypoint15 waypoint22)
(visible waypoint22 waypoint15)
(visible waypoint15 waypoint23)
(visible waypoint23 waypoint15)
(visible waypoint15 waypoint27)
(visible waypoint27 waypoint15)
(visible waypoint15 waypoint28)
(visible waypoint28 waypoint15)
(visible waypoint16 waypoint9)
(visible waypoint9 waypoint16)
(visible waypoint16 waypoint14)
(visible waypoint14 waypoint16)
(visible waypoint17 waypoint10)
(visible waypoint10 waypoint17)
(visible waypoint17 waypoint24)
(visible waypoint24 waypoint17)
(visible waypoint17 waypoint25)
(visible waypoint25 waypoint17)
(visible waypoint18 waypoint10)
(visible waypoint10 waypoint18)
(visible waypoint18 waypoint14)
(visible waypoint14 waypoint18)
(visible waypoint18 waypoint16)
(visible waypoint16 waypoint18)
(visible waypoint18 waypoint27)
(visible waypoint27 waypoint18)
(visible waypoint19 waypoint7)
(visible waypoint7 waypoint19)
(visible waypoint19 waypoint10)
(visible waypoint10 waypoint19)
(visible waypoint19 waypoint12)
(visible waypoint12 waypoint19)
(visible waypoint19 waypoint15)
(visible waypoint15 waypoint19)
(visible waypoint19 waypoint21)
(visible waypoint21 waypoint19)
(visible waypoint20 waypoint8)
(visible waypoint8 waypoint20)
(visible waypoint20 waypoint11)
(visible waypoint11 waypoint20)
(visible waypoint20 waypoint15)
(visible waypoint15 waypoint20)
(visible waypoint20 waypoint16)
(visible waypoint16 waypoint20)
(visible waypoint20 waypoint21)
(visible waypoint21 waypoint20)
(visible waypoint20 waypoint28)
(visible waypoint28 waypoint20)
(visible waypoint21 waypoint2)
(visible waypoint2 waypoint21)
(visible waypoint21 waypoint3)
(visible waypoint3 waypoint21)
(visible waypoint21 waypoint8)
(visible waypoint8 waypoint21)
(visible waypoint21 waypoint13)
(visible waypoint13 waypoint21)
(visible waypoint21 waypoint22)
(visible waypoint22 waypoint21)
(visible waypoint21 waypoint23)
(visible waypoint23 waypoint21)
(visible waypoint21 waypoint26)
(visible waypoint26 waypoint21)
(visible waypoint22 waypoint18)
(visible waypoint18 waypoint22)
(visible waypoint22 waypoint28)
(visible waypoint28 waypoint22)
(visible waypoint22 waypoint29)
(visible waypoint29 waypoint22)
(visible waypoint23 waypoint1)
(visible waypoint1 waypoint23)
(visible waypoint23 waypoint17)
(visible waypoint17 waypoint23)
(visible waypoint23 waypoint28)
(visible waypoint28 waypoint23)
(visible waypoint24 waypoint8)
(visible waypoint8 waypoint24)
(visible waypoint24 waypoint10)
(visible waypoint10 waypoint24)
(visible waypoint24 waypoint13)
(visible waypoint13 waypoint24)
(visible waypoint24 waypoint15)
(visible waypoint15 waypoint24)
(visible waypoint24 waypoint21)
(visible waypoint21 waypoint24)
(visible waypoint24 waypoint22)
(visible waypoint22 waypoint24)
(visible waypoint25 waypoint2)
(visible waypoint2 waypoint25)
(visible waypoint25 waypoint14)
(visible waypoint14 waypoint25)
(visible waypoint26 waypoint9)
(visible waypoint9 waypoint26)
(visible waypoint26 waypoint10)
(visible waypoint10 waypoint26)
(visible waypoint26 waypoint22)
(visible waypoint22 waypoint26)
(visible waypoint27 waypoint22)
(visible waypoint22 waypoint27)
(visible waypoint27 waypoint24)
(visible waypoint24 waypoint27)
(visible waypoint27 waypoint28)
(visible waypoint28 waypoint27)
(visible waypoint28 waypoint6)
(visible waypoint6 waypoint28)
(visible waypoint28 waypoint17)
(visible waypoint17 waypoint28)
(visible waypoint28 waypoint24)
(visible waypoint24 waypoint28)
(visible waypoint28 waypoint25)
(visible waypoint25 waypoint28)
(visible waypoint28 waypoint29)
(visible waypoint29 waypoint28)
(visible waypoint29 waypoint7)
(visible waypoint7 waypoint29)
(visible waypoint29 waypoint10)
(visible waypoint10 waypoint29)
(visible waypoint29 waypoint19)
(visible waypoint19 waypoint29)
(at_soil_sample waypoint0)
(at_soil_sample waypoint1)
(at_soil_sample waypoint2)
(at_soil_sample waypoint3)
(at_rock_sample waypoint3)
(at_rock_sample waypoint4)
(at_rock_sample waypoint6)
(at_rock_sample waypoint8)
(at_rock_sample waypoint9)
(at_rock_sample waypoint10)
(at_soil_sample waypoint11)
(at_soil_sample waypoint12)
(at_rock_sample waypoint12)
(at_rock_sample waypoint14)
(at_rock_sample waypoint15)
(at_rock_sample waypoint19)
(at_rock_sample waypoint20)
(at_soil_sample waypoint21)
(at_soil_sample waypoint23)
(at_soil_sample waypoint24)
(at_rock_sample waypoint24)
(at_soil_sample waypoint25)
(at_rock_sample waypoint25)
(at_rock_sample waypoint26)
(at_rock_sample waypoint28)
(at_rock_sample waypoint29)
(at_lander general waypoint27)
(channel_free general)
(at rover0 waypoint14)
(available rover0)
(store_of rover0store rover0)
(empty rover0store)
(equipped_for_rock_analysis rover0)
(equipped_for_imaging rover0)
(can_traverse rover0 waypoint14 waypoint5)
(can_traverse rover0 waypoint5 waypoint14)
(can_traverse rover0 waypoint14 waypoint6)
(can_traverse rover0 waypoint6 waypoint14)
(can_traverse rover0 waypoint14 waypoint7)
(can_traverse rover0 waypoint7 waypoint14)
(can_traverse rover0 waypoint14 waypoint8)
(can_traverse rover0 waypoint8 waypoint14)
(can_traverse rover0 waypoint14 waypoint16)
(can_traverse rover0 waypoint16 waypoint14)
(can_traverse rover0 waypoint14 waypoint18)
(can_traverse rover0 waypoint18 waypoint14)
(can_traverse rover0 waypoint14 waypoint25)
(can_traverse rover0 waypoint25 waypoint14)
(can_traverse rover0 waypoint5 waypoint1)
(can_traverse rover0 waypoint1 waypoint5)
(can_traverse rover0 waypoint5 waypoint11)
(can_traverse rover0 waypoint11 waypoint5)
(can_traverse rover0 waypoint5 waypoint13)
(can_traverse rover0 waypoint13 waypoint5)
(can_traverse rover0 waypoint5 waypoint23)
(can_traverse rover0 waypoint23 waypoint5)
(can_traverse rover0 waypoint6 waypoint4)
(can_traverse rover0 waypoint4 waypoint6)
(can_traverse rover0 waypoint6 waypoint19)
(can_traverse rover0 waypoint19 waypoint6)
(can_traverse rover0 waypoint6 waypoint28)
(can_traverse rover0 waypoint28 waypoint6)
(can_traverse rover0 waypoint7 waypoint20)
(can_traverse rover0 waypoint20 waypoint7)
(can_traverse rover0 waypoint7 waypoint21)
(can_traverse rover0 waypoint21 waypoint7)
(can_traverse rover0 waypoint7 waypoint27)
(can_traverse rover0 waypoint27 waypoint7)
(can_traverse rover0 waypoint8 waypoint0)
(can_traverse rover0 waypoint0 waypoint8)
(can_traverse rover0 waypoint8 waypoint2)
(can_traverse rover0 waypoint2 waypoint8)
(can_traverse rover0 waypoint8 waypoint10)
(can_traverse rover0 waypoint10 waypoint8)
(can_traverse rover0 waypoint8 waypoint15)
(can_traverse rover0 waypoint15 waypoint8)
(can_traverse rover0 waypoint8 waypoint24)
(can_traverse rover0 waypoint24 waypoint8)
(can_traverse rover0 waypoint16 waypoint9)
(can_traverse rover0 waypoint9 waypoint16)
(can_traverse rover0 waypoint25 waypoint17)
(can_traverse rover0 waypoint17 waypoint25)
(can_traverse rover0 waypoint1 waypoint12)
(can_traverse rover0 waypoint12 waypoint1)
(can_traverse rover0 waypoint13 waypoint3)
(can_traverse rover0 waypoint3 waypoint13)
(can_traverse rover0 waypoint28 waypoint22)
(can_traverse rover0 waypoint22 waypoint28)
(can_traverse rover0 waypoint28 waypoint29)
(can_traverse rover0 waypoint29 waypoint28)
(can_traverse rover0 waypoint21 waypoint26)
(can_traverse rover0 waypoint26 waypoint21)
(at rover1 waypoint14)
(available rover1)
(store_of rover1store rover1)
(empty rover1store)
(equipped_for_imaging rover1)
(can_traverse rover1 waypoint14 waypoint5)
(can_traverse rover1 waypoint5 waypoint14)
(can_traverse rover1 waypoint14 waypoint6)
(can_traverse rover1 waypoint6 waypoint14)
(can_traverse rover1 waypoint14 waypoint7)
(can_traverse rover1 waypoint7 waypoint14)
(can_traverse rover1 waypoint14 waypoint8)
(can_traverse rover1 waypoint8 waypoint14)
(can_traverse rover1 waypoint14 waypoint10)
(can_traverse rover1 waypoint10 waypoint14)
(can_traverse rover1 waypoint14 waypoint16)
(can_traverse rover1 waypoint16 waypoint14)
(can_traverse rover1 waypoint14 waypoint18)
(can_traverse rover1 waypoint18 waypoint14)
(can_traverse rover1 waypoint14 waypoint21)
(can_traverse rover1 waypoint21 waypoint14)
(can_traverse rover1 waypoint14 waypoint25)
(can_traverse rover1 waypoint25 waypoint14)
(can_traverse rover1 waypoint5 waypoint1)
(can_traverse rover1 waypoint1 waypoint5)
(can_traverse rover1 waypoint5 waypoint11)
(can_traverse rover1 waypoint11 waypoint5)
(can_traverse rover1 waypoint5 waypoint13)
(can_traverse rover1 waypoint13 waypoint5)
(can_traverse rover1 waypoint5 waypoint19)
(can_traverse rover1 waypoint19 waypoint5)
(can_traverse rover1 waypoint5 waypoint23)
(can_traverse rover1 waypoint23 waypoint5)
(can_traverse rover1 waypoint6 waypoint22)
(can_traverse rover1 waypoint22 waypoint6)
(can_traverse rover1 waypoint6 waypoint28)
(can_traverse rover1 waypoint28 waypoint6)
(can_traverse rover1 waypoint7 waypoint27)
(can_traverse rover1 waypoint27 waypoint7)
(can_traverse rover1 waypoint8 waypoint0)
(can_traverse rover1 waypoint0 waypoint8)
(can_traverse rover1 waypoint8 waypoint2)
(can_traverse rover1 waypoint2 waypoint8)
(can_traverse rover1 waypoint8 waypoint15)
(can_traverse rover1 waypoint15 waypoint8)
(can_traverse rover1 waypoint8 waypoint24)
(can_traverse rover1 waypoint24 waypoint8)
(can_traverse rover1 waypoint10 waypoint4)
(can_traverse rover1 waypoint4 waypoint10)
(can_traverse rover1 waypoint10 waypoint9)
(can_traverse rover1 waypoint9 waypoint10)
(can_traverse rover1 waypoint10 waypoint17)
(can_traverse rover1 waypoint17 waypoint10)
(can_traverse rover1 waypoint10 waypoint20)
(can_traverse rover1 waypoint20 waypoint10)
(can_traverse rover1 waypoint10 waypoint26)
(can_traverse rover1 waypoint26 waypoint10)
(can_traverse rover1 waypoint10 waypoint29)
(can_traverse rover1 waypoint29 waypoint10)
(can_traverse rover1 waypoint16 waypoint12)
(can_traverse rover1 waypoint12 waypoint16)
(can_traverse rover1 waypoint21 waypoint3)
(can_traverse rover1 waypoint3 waypoint21)
(at rover2 waypoint16)
(available rover2)
(store_of rover2store rover2)
(empty rover2store)
(equipped_for_soil_analysis rover2)
(equipped_for_rock_analysis rover2)
(can_traverse rover2 waypoint16 waypoint2)
(can_traverse rover2 waypoint2 waypoint16)
(can_traverse rover2 waypoint16 waypoint11)
(can_traverse rover2 waypoint11 waypoint16)
(can_traverse rover2 waypoint16 waypoint14)
(can_traverse rover2 waypoint14 waypoint16)
(can_traverse rover2 waypoint16 waypoint18)
(can_traverse rover2 waypoint18 waypoint16)
(can_traverse rover2 waypoint2 waypoint9)
(can_traverse rover2 waypoint9 waypoint2)
(can_traverse rover2 waypoint2 waypoint21)
(can_traverse rover2 waypoint21 waypoint2)
(can_traverse rover2 waypoint2 waypoint24)
(can_traverse rover2 waypoint24 waypoint2)
(can_traverse rover2 waypoint2 waypoint25)
(can_traverse rover2 waypoint25 waypoint2)
(can_traverse rover2 waypoint11 waypoint0)
(can_traverse rover2 waypoint0 waypoint11)
(can_traverse rover2 waypoint14 waypoint5)
(can_traverse rover2 waypoint5 waypoint14)
(can_traverse rover2 waypoint14 waypoint6)
(can_traverse rover2 waypoint6 waypoint14)
(can_traverse rover2 waypoint14 waypoint7)
(can_traverse rover2 waypoint7 waypoint14)
(can_traverse rover2 waypoint14 waypoint8)
(can_traverse rover2 waypoint8 waypoint14)
(can_traverse rover2 waypoint18 waypoint22)
(can_traverse rover2 waypoint22 waypoint18)
(can_traverse rover2 waypoint18 waypoint27)
(can_traverse rover2 waypoint27 waypoint18)
(can_traverse rover2 waypoint9 waypoint4)
(can_traverse rover2 waypoint4 waypoint9)
(can_traverse rover2 waypoint9 waypoint10)
(can_traverse rover2 waypoint10 waypoint9)
(can_traverse rover2 waypoint9 waypoint12)
(can_traverse rover2 waypoint12 waypoint9)
(can_traverse rover2 waypoint9 waypoint26)
(can_traverse rover2 waypoint26 waypoint9)
(can_traverse rover2 waypoint21 waypoint3)
(can_traverse rover2 waypoint3 waypoint21)
(can_traverse rover2 waypoint21 waypoint19)
(can_traverse rover2 waypoint19 waypoint21)
(can_traverse rover2 waypoint24 waypoint13)
(can_traverse rover2 waypoint13 waypoint24)
(can_traverse rover2 waypoint24 waypoint28)
(can_traverse rover2 waypoint28 waypoint24)
(can_traverse rover2 waypoint25 waypoint1)
(can_traverse rover2 waypoint1 waypoint25)
(can_traverse rover2 waypoint25 waypoint17)
(can_traverse rover2 waypoint17 waypoint25)
(at rover3 waypoint3)
(available rover3)
(store_of rover3store rover3)
(empty rover3store)
(equipped_for_soil_analysis rover3)
(equipped_for_rock_analysis rover3)
(equipped_for_imaging rover3)
(can_traverse rover3 waypoint3 waypoint10)
(can_traverse rover3 waypoint10 waypoint3)
(can_traverse rover3 waypoint3 waypoint13)
(can_traverse rover3 waypoint13 waypoint3)
(can_traverse rover3 waypoint3 waypoint27)
(can_traverse rover3 waypoint27 waypoint3)
(can_traverse rover3 waypoint10 waypoint4)
(can_traverse rover3 waypoint4 waypoint10)
(can_traverse rover3 waypoint10 waypoint9)
(can_traverse rover3 waypoint9 waypoint10)
(can_traverse rover3 waypoint10 waypoint14)
(can_traverse rover3 waypoint14 waypoint10)
(can_traverse rover3 waypoint10 waypoint17)
(can_traverse rover3 waypoint17 waypoint10)
(can_traverse rover3 waypoint10 waypoint18)
(can_traverse rover3 waypoint18 waypoint10)
(can_traverse rover3 waypoint10 waypoint19)
(can_traverse rover3 waypoint19 waypoint10)
(can_traverse rover3 waypoint10 waypoint20)
(can_traverse rover3 waypoint20 waypoint10)
(can_traverse rover3 waypoint10 waypoint21)
(can_traverse rover3 waypoint21 waypoint10)
(can_traverse rover3 waypoint10 waypoint26)
(can_traverse rover3 waypoint26 waypoint10)
(can_traverse rover3 waypoint10 waypoint29)
(can_traverse rover3 waypoint29 waypoint10)
(can_traverse rover3 waypoint27 waypoint7)
(can_traverse rover3 waypoint7 waypoint27)
(can_traverse rover3 waypoint27 waypoint8)
(can_traverse rover3 waypoint8 waypoint27)
(can_traverse rover3 waypoint27 waypoint15)
(can_traverse rover3 waypoint15 waypoint27)
(can_traverse rover3 waypoint27 waypoint24)
(can_traverse rover3 waypoint24 waypoint27)
(can_traverse rover3 waypoint4 waypoint6)
(can_traverse rover3 waypoint6 waypoint4)
(can_traverse rover3 waypoint4 waypoint12)
(can_traverse rover3 waypoint12 waypoint4)
(can_traverse rover3 waypoint9 waypoint16)
(can_traverse rover3 waypoint16 waypoint9)
(can_traverse rover3 waypoint14 waypoint5)
(can_traverse rover3 waypoint5 waypoint14)
(can_traverse rover3 waypoint17 waypoint23)
(can_traverse rover3 waypoint23 waypoint17)
(can_traverse rover3 waypoint17 waypoint28)
(can_traverse rover3 waypoint28 waypoint17)
(can_traverse rover3 waypoint18 waypoint22)
(can_traverse rover3 waypoint22 waypoint18)
(can_traverse rover3 waypoint21 waypoint2)
(can_traverse rover3 waypoint2 waypoint21)
(can_traverse rover3 waypoint29 waypoint0)
(can_traverse rover3 waypoint0 waypoint29)
(can_traverse rover3 waypoint8 waypoint25)
(can_traverse rover3 waypoint25 waypoint8)
(can_traverse rover3 waypoint6 waypoint11)
(can_traverse rover3 waypoint11 waypoint6)
(can_traverse rover3 waypoint23 waypoint1)
(can_traverse rover3 waypoint1 waypoint23)
(at rover4 waypoint18)
(available rover4)
(store_of rover4store rover4)
(empty rover4store)
(equipped_for_rock_analysis rover4)
(equipped_for_imaging rover4)
(can_traverse rover4 waypoint18 waypoint10)
(can_traverse rover4 waypoint10 waypoint18)
(can_traverse rover4 waypoint18 waypoint11)
(can_traverse rover4 waypoint11 waypoint18)
(can_traverse rover4 waypoint18 waypoint14)
(can_traverse rover4 waypoint14 waypoint18)
(can_traverse rover4 waypoint18 waypoint16)
(can_traverse rover4 waypoint16 waypoint18)
(can_traverse rover4 waypoint18 waypoint22)
(can_traverse rover4 waypoint22 waypoint18)
(can_traverse rover4 waypoint18 waypoint27)
(can_traverse rover4 waypoint27 waypoint18)
(can_traverse rover4 waypoint10 waypoint3)
(can_traverse rover4 waypoint3 waypoint10)
(can_traverse rover4 waypoint10 waypoint4)
(can_traverse rover4 waypoint4 waypoint10)
(can_traverse rover4 waypoint10 waypoint8)
(can_traverse rover4 waypoint8 waypoint10)
(can_traverse rover4 waypoint10 waypoint9)
(can_traverse rover4 waypoint9 waypoint10)
(can_traverse rover4 waypoint10 waypoint19)
(can_traverse rover4 waypoint19 waypoint10)
(can_traverse rover4 waypoint10 waypoint20)
(can_traverse rover4 waypoint20 waypoint10)
(can_traverse rover4 waypoint10 waypoint21)
(can_traverse rover4 waypoint21 waypoint10)
(can_traverse rover4 waypoint10 waypoint23)
(can_traverse rover4 waypoint23 waypoint10)
(can_traverse rover4 waypoint10 waypoint24)
(can_traverse rover4 waypoint24 waypoint10)
(can_traverse rover4 waypoint10 waypoint26)
(can_traverse rover4 waypoint26 waypoint10)
(can_traverse rover4 waypoint10 waypoint29)
(can_traverse rover4 waypoint29 waypoint10)
(can_traverse rover4 waypoint11 waypoint0)
(can_traverse rover4 waypoint0 waypoint11)
(can_traverse rover4 waypoint11 waypoint5)
(can_traverse rover4 waypoint5 waypoint11)
(can_traverse rover4 waypoint11 waypoint6)
(can_traverse rover4 waypoint6 waypoint11)
(can_traverse rover4 waypoint14 waypoint7)
(can_traverse rover4 waypoint7 waypoint14)
(can_traverse rover4 waypoint14 waypoint25)
(can_traverse rover4 waypoint25 waypoint14)
(can_traverse rover4 waypoint16 waypoint2)
(can_traverse rover4 waypoint2 waypoint16)
(can_traverse rover4 waypoint22 waypoint15)
(can_traverse rover4 waypoint15 waypoint22)
(can_traverse rover4 waypoint27 waypoint28)
(can_traverse rover4 waypoint28 waypoint27)
(can_traverse rover4 waypoint3 waypoint13)
(can_traverse rover4 waypoint13 waypoint3)
(can_traverse rover4 waypoint4 waypoint1)
(can_traverse rover4 waypoint1 waypoint4)
(can_traverse rover4 waypoint4 waypoint12)
(can_traverse rover4 waypoint12 waypoint4)
(can_traverse rover4 waypoint23 waypoint17)
(can_traverse rover4 waypoint17 waypoint23)
(at rover5 waypoint27)
(available rover5)
(store_of rover5store rover5)
(empty rover5store)
(equipped_for_imaging rover5)
(can_traverse rover5 waypoint27 waypoint3)
(can_traverse rover5 waypoint3 waypoint27)
(can_traverse rover5 waypoint27 waypoint8)
(can_traverse rover5 waypoint8 waypoint27)
(can_traverse rover5 waypoint27 waypoint15)
(can_traverse rover5 waypoint15 waypoint27)
(can_traverse rover5 waypoint27 waypoint18)
(can_traverse rover5 waypoint18 waypoint27)
(can_traverse rover5 waypoint27 waypoint22)
(can_traverse rover5 waypoint22 waypoint27)
(can_traverse rover5 waypoint27 waypoint28)
(can_traverse rover5 waypoint28 waypoint27)
(can_traverse rover5 waypoint3 waypoint21)
(can_traverse rover5 waypoint21 waypoint3)
(can_traverse rover5 waypoint8 waypoint0)
(can_traverse rover5 waypoint0 waypoint8)
(can_traverse rover5 waypoint8 waypoint10)
(can_traverse rover5 waypoint10 waypoint8)
(can_traverse rover5 waypoint8 waypoint14)
(can_traverse rover5 waypoint14 waypoint8)
(can_traverse rover5 waypoint8 waypoint24)
(can_traverse rover5 waypoint24 waypoint8)
(can_traverse rover5 waypoint8 waypoint25)
(can_traverse rover5 waypoint25 waypoint8)
(can_traverse rover5 waypoint15 waypoint1)
(can_traverse rover5 waypoint1 waypoint15)
(can_traverse rover5 waypoint15 waypoint19)
(can_traverse rover5 waypoint19 waypoint15)
(can_traverse rover5 waypoint15 waypoint20)
(can_traverse rover5 waypoint20 waypoint15)
(can_traverse rover5 waypoint15 waypoint23)
(can_traverse rover5 waypoint23 waypoint15)
(can_traverse rover5 waypoint18 waypoint11)
(can_traverse rover5 waypoint11 waypoint18)
(can_traverse rover5 waypoint22 waypoint6)
(can_traverse rover5 waypoint6 waypoint22)
(can_traverse rover5 waypoint22 waypoint26)
(can_traverse rover5 waypoint26 waypoint22)
(can_traverse rover5 waypoint28 waypoint17)
(can_traverse rover5 waypoint17 waypoint28)
(can_traverse rover5 waypoint28 waypoint29)
(can_traverse rover5 waypoint29 waypoint28)
(can_traverse rover5 waypoint21 waypoint2)
(can_traverse rover5 waypoint2 waypoint21)
(can_traverse rover5 waypoint21 waypoint13)
(can_traverse rover5 waypoint13 waypoint21)
(can_traverse rover5 waypoint10 waypoint9)
(can_traverse rover5 waypoint9 waypoint10)
(can_traverse rover5 waypoint14 waypoint7)
(can_traverse rover5 waypoint7 waypoint14)
(can_traverse rover5 waypoint14 waypoint16)
(can_traverse rover5 waypoint16 waypoint14)
(can_traverse rover5 waypoint1 waypoint5)
(can_traverse rover5 waypoint5 waypoint1)
(can_traverse rover5 waypoint1 waypoint12)
(can_traverse rover5 waypoint12 waypoint1)
(can_traverse rover5 waypoint6 waypoint4)
(can_traverse rover5 waypoint4 waypoint6)
(at rover6 waypoint3)
(available rover6)
(store_of rover6store rover6)
(empty rover6store)
(equipped_for_soil_analysis rover6)
(equipped_for_rock_analysis rover6)
(can_traverse rover6 waypoint3 waypoint10)
(can_traverse rover6 waypoint10 waypoint3)
(can_traverse rover6 waypoint3 waypoint13)
(can_traverse rover6 waypoint13 waypoint3)
(can_traverse rover6 waypoint3 waypoint21)
(can_traverse rover6 waypoint21 waypoint3)
(can_traverse rover6 waypoint10 waypoint4)
(can_traverse rover6 waypoint4 waypoint10)
(can_traverse rover6 waypoint10 waypoint8)
(can_traverse rover6 waypoint8 waypoint10)
(can_traverse rover6 waypoint10 waypoint14)
(can_traverse rover6 waypoint14 waypoint10)
(can_traverse rover6 waypoint10 waypoint15)
(can_traverse rover6 waypoint15 waypoint10)
(can_traverse rover6 waypoint10 waypoint17)
(can_traverse rover6 waypoint17 waypoint10)
(can_traverse rover6 waypoint10 waypoint18)
(can_traverse rover6 waypoint18 waypoint10)
(can_traverse rover6 waypoint10 waypoint19)
(can_traverse rover6 waypoint19 waypoint10)
(can_traverse rover6 waypoint10 waypoint20)
(can_traverse rover6 waypoint20 waypoint10)
(can_traverse rover6 waypoint10 waypoint24)
(can_traverse rover6 waypoint24 waypoint10)
(can_traverse rover6 waypoint10 waypoint29)
(can_traverse rover6 waypoint29 waypoint10)
(can_traverse rover6 waypoint13 waypoint5)
(can_traverse rover6 waypoint5 waypoint13)
(can_traverse rover6 waypoint21 waypoint2)
(can_traverse rover6 waypoint2 waypoint21)
(can_traverse rover6 waypoint21 waypoint7)
(can_traverse rover6 waypoint7 waypoint21)
(can_traverse rover6 waypoint21 waypoint22)
(can_traverse rover6 waypoint22 waypoint21)
(can_traverse rover6 waypoint21 waypoint23)
(can_traverse rover6 waypoint23 waypoint21)
(can_traverse rover6 waypoint21 waypoint26)
(can_traverse rover6 waypoint26 waypoint21)
(can_traverse rover6 waypoint4 waypoint6)
(can_traverse rover6 waypoint6 waypoint4)
(can_traverse rover6 waypoint4 waypoint9)
(can_traverse rover6 waypoint9 waypoint4)
(can_traverse rover6 waypoint4 waypoint12)
(can_traverse rover6 waypoint12 waypoint4)
(can_traverse rover6 waypoint8 waypoint0)
(can_traverse rover6 waypoint0 waypoint8)
(can_traverse rover6 waypoint8 waypoint25)
(can_traverse rover6 waypoint25 waypoint8)
(can_traverse rover6 waypoint8 waypoint27)
(can_traverse rover6 waypoint27 waypoint8)
(can_traverse rover6 waypoint15 waypoint1)
(can_traverse rover6 waypoint1 waypoint15)
(can_traverse rover6 waypoint15 waypoint28)
(can_traverse rover6 waypoint28 waypoint15)
(can_traverse rover6 waypoint18 waypoint16)
(can_traverse rover6 waypoint16 waypoint18)
(can_traverse rover6 waypoint20 waypoint11)
(can_traverse rover6 waypoint11 waypoint20)
(at rover7 waypoint29)
(available rover7)
(store_of rover7store rover7)
(empty rover7store)
(equipped_for_soil_analysis rover7)
(equipped_for_rock_analysis rover7)
(equipped_for_imaging rover7)
(can_traverse rover7 waypoint29 waypoint0)
(can_traverse rover7 waypoint0 waypoint29)
(can_traverse rover7 waypoint29 waypoint7)
(can_traverse rover7 waypoint7 waypoint29)
(can_traverse rover7 waypoint29 waypoint10)
(can_traverse rover7 waypoint10 waypoint29)
(can_traverse rover7 waypoint29 waypoint19)
(can_traverse rover7 waypoint19 waypoint29)
(can_traverse rover7 waypoint29 waypoint22)
(can_traverse rover7 waypoint22 waypoint29)
(can_traverse rover7 waypoint29 waypoint28)
(can_traverse rover7 waypoint28 waypoint29)
(can_traverse rover7 waypoint0 waypoint1)
(can_traverse rover7 waypoint1 waypoint0)
(can_traverse rover7 waypoint0 waypoint8)
(can_traverse rover7 waypoint8 waypoint0)
(can_traverse rover7 waypoint7 waypoint5)
(can_traverse rover7 waypoint5 waypoint7)
(can_traverse rover7 waypoint7 waypoint6)
(can_traverse rover7 waypoint6 waypoint7)
(can_traverse rover7 waypoint7 waypoint14)
(can_traverse rover7 waypoint14 waypoint7)
(can_traverse rover7 waypoint7 waypoint20)
(can_traverse rover7 waypoint20 waypoint7)
(can_traverse rover7 waypoint7 waypoint21)
(can_traverse rover7 waypoint21 waypoint7)
(can_traverse rover7 waypoint7 waypoint23)
(can_traverse rover7 waypoint23 waypoint7)
(can_traverse rover7 waypoint10 waypoint3)
(can_traverse rover7 waypoint3 waypoint10)
(can_traverse rover7 waypoint10 waypoint9)
(can_traverse rover7 waypoint9 waypoint10)
(can_traverse rover7 waypoint10 waypoint15)
(can_traverse rover7 waypoint15 waypoint10)
(can_traverse rover7 waypoint10 waypoint17)
(can_traverse rover7 waypoint17 waypoint10)
(can_traverse rover7 waypoint10 waypoint18)
(can_traverse rover7 waypoint18 waypoint10)
(can_traverse rover7 waypoint10 waypoint24)
(can_traverse rover7 waypoint24 waypoint10)
(can_traverse rover7 waypoint10 waypoint26)
(can_traverse rover7 waypoint26 waypoint10)
(can_traverse rover7 waypoint22 waypoint27)
(can_traverse rover7 waypoint27 waypoint22)
(can_traverse rover7 waypoint28 waypoint25)
(can_traverse rover7 waypoint25 waypoint28)
(can_traverse rover7 waypoint1 waypoint12)
(can_traverse rover7 waypoint12 waypoint1)
(can_traverse rover7 waypoint5 waypoint11)
(can_traverse rover7 waypoint11 waypoint5)
(can_traverse rover7 waypoint6 waypoint4)
(can_traverse rover7 waypoint4 waypoint6)
(can_traverse rover7 waypoint14 waypoint16)
(can_traverse rover7 waypoint16 waypoint14)
(can_traverse rover7 waypoint20 waypoint13)
(can_traverse rover7 waypoint13 waypoint20)
(can_traverse rover7 waypoint21 waypoint2)
(can_traverse rover7 waypoint2 waypoint21)
(at rover8 waypoint3)
(available rover8)
(store_of rover8store rover8)
(empty rover8store)
(equipped_for_soil_analysis rover8)
(equipped_for_rock_analysis rover8)
(can_traverse rover8 waypoint3 waypoint10)
(can_traverse rover8 waypoint10 waypoint3)
(can_traverse rover8 waypoint3 waypoint21)
(can_traverse rover8 waypoint21 waypoint3)
(can_traverse rover8 waypoint3 waypoint26)
(can_traverse rover8 waypoint26 waypoint3)
(can_traverse rover8 waypoint3 waypoint27)
(can_traverse rover8 waypoint27 waypoint3)
(can_traverse rover8 waypoint10 waypoint4)
(can_traverse rover8 waypoint4 waypoint10)
(can_traverse rover8 waypoint10 waypoint8)
(can_traverse rover8 waypoint8 waypoint10)
(can_traverse rover8 waypoint10 waypoint9)
(can_traverse rover8 waypoint9 waypoint10)
(can_traverse rover8 waypoint10 waypoint14)
(can_traverse rover8 waypoint14 waypoint10)
(can_traverse rover8 waypoint10 waypoint15)
(can_traverse rover8 waypoint15 waypoint10)
(can_traverse rover8 waypoint10 waypoint17)
(can_traverse rover8 waypoint17 waypoint10)
(can_traverse rover8 waypoint10 waypoint18)
(can_traverse rover8 waypoint18 waypoint10)
(can_traverse rover8 waypoint10 waypoint19)
(can_traverse rover8 waypoint19 waypoint10)
(can_traverse rover8 waypoint10 waypoint23)
(can_traverse rover8 waypoint23 waypoint10)
(can_traverse rover8 waypoint10 waypoint24)
(can_traverse rover8 waypoint24 waypoint10)
(can_traverse rover8 waypoint10 waypoint29)
(can_traverse rover8 waypoint29 waypoint10)
(can_traverse rover8 waypoint21 waypoint2)
(can_traverse rover8 waypoint2 waypoint21)
(can_traverse rover8 waypoint21 waypoint7)
(can_traverse rover8 waypoint7 waypoint21)
(can_traverse rover8 waypoint21 waypoint13)
(can_traverse rover8 waypoint13 waypoint21)
(can_traverse rover8 waypoint21 waypoint22)
(can_traverse rover8 waypoint22 waypoint21)
(can_traverse rover8 waypoint27 waypoint28)
(can_traverse rover8 waypoint28 waypoint27)
(can_traverse rover8 waypoint4 waypoint1)
(can_traverse rover8 waypoint1 waypoint4)
(can_traverse rover8 waypoint4 waypoint6)
(can_traverse rover8 waypoint6 waypoint4)
(can_traverse rover8 waypoint8 waypoint0)
(can_traverse rover8 waypoint0 waypoint8)
(can_traverse rover8 waypoint8 waypoint20)
(can_traverse rover8 waypoint20 waypoint8)
(can_traverse rover8 waypoint9 waypoint12)
(can_traverse rover8 waypoint12 waypoint9)
(can_traverse rover8 waypoint9 waypoint16)
(can_traverse rover8 waypoint16 waypoint9)
(can_traverse rover8 waypoint14 waypoint25)
(can_traverse rover8 waypoint25 waypoint14)
(can_traverse rover8 waypoint18 waypoint11)
(can_traverse rover8 waypoint11 waypoint18)
(can_traverse rover8 waypoint19 waypoint5)
(can_traverse rover8 waypoint5 waypoint19)
(at rover9 waypoint9)
(available rover9)
(store_of rover9store rover9)
(empty rover9store)
(equipped_for_soil_analysis rover9)
(equipped_for_imaging rover9)
(can_traverse rover9 waypoint9 waypoint2)
(can_traverse rover9 waypoint2 waypoint9)
(can_traverse rover9 waypoint9 waypoint4)
(can_traverse rover9 waypoint4 waypoint9)
(can_traverse rover9 waypoint9 waypoint10)
(can_traverse rover9 waypoint10 waypoint9)
(can_traverse rover9 waypoint9 waypoint12)
(can_traverse rover9 waypoint12 waypoint9)
(can_traverse rover9 waypoint9 waypoint24)
(can_traverse rover9 waypoint24 waypoint9)
(can_traverse rover9 waypoint9 waypoint26)
(can_traverse rover9 waypoint26 waypoint9)
(can_traverse rover9 waypoint2 waypoint8)
(can_traverse rover9 waypoint8 waypoint2)
(can_traverse rover9 waypoint2 waypoint16)
(can_traverse rover9 waypoint16 waypoint2)
(can_traverse rover9 waypoint2 waypoint21)
(can_traverse rover9 waypoint21 waypoint2)
(can_traverse rover9 waypoint2 waypoint25)
(can_traverse rover9 waypoint25 waypoint2)
(can_traverse rover9 waypoint4 waypoint6)
(can_traverse rover9 waypoint6 waypoint4)
(can_traverse rover9 waypoint10 waypoint14)
(can_traverse rover9 waypoint14 waypoint10)
(can_traverse rover9 waypoint10 waypoint15)
(can_traverse rover9 waypoint15 waypoint10)
(can_traverse rover9 waypoint10 waypoint17)
(can_traverse rover9 waypoint17 waypoint10)
(can_traverse rover9 waypoint10 waypoint20)
(can_traverse rover9 waypoint20 waypoint10)
(can_traverse rover9 waypoint10 waypoint29)
(can_traverse rover9 waypoint29 waypoint10)
(can_traverse rover9 waypoint12 waypoint1)
(can_traverse rover9 waypoint1 waypoint12)
(can_traverse rover9 waypoint12 waypoint19)
(can_traverse rover9 waypoint19 waypoint12)
(can_traverse rover9 waypoint24 waypoint22)
(can_traverse rover9 waypoint22 waypoint24)
(can_traverse rover9 waypoint24 waypoint27)
(can_traverse rover9 waypoint27 waypoint24)
(can_traverse rover9 waypoint24 waypoint28)
(can_traverse rover9 waypoint28 waypoint24)
(can_traverse rover9 waypoint8 waypoint0)
(can_traverse rover9 waypoint0 waypoint8)
(can_traverse rover9 waypoint16 waypoint11)
(can_traverse rover9 waypoint11 waypoint16)
(can_traverse rover9 waypoint21 waypoint3)
(can_traverse rover9 waypoint3 waypoint21)
(can_traverse rover9 waypoint21 waypoint13)
(can_traverse rover9 waypoint13 waypoint21)
(can_traverse rover9 waypoint21 waypoint23)
(can_traverse rover9 waypoint23 waypoint21)
(can_traverse rover9 waypoint6 waypoint5)
(can_traverse rover9 waypoint5 waypoint6)
(can_traverse rover9 waypoint14 waypoint7)
(can_traverse rover9 waypoint7 waypoint14)
(can_traverse rover9 waypoint14 waypoint18)
(can_traverse rover9 waypoint18 waypoint14)
(on_board camera0 rover5)
(calibration_target camera0 objective3)
(supports camera0 high_res)
(supports camera0 low_res)
(on_board camera1 rover3)
(calibration_target camera1 objective3)
(supports camera1 high_res)
(on_board camera2 rover4)
(calibration_target camera2 objective0)
(supports camera2 colour)
(supports camera2 high_res)
(supports camera2 low_res)
(on_board camera3 rover7)
(calibration_target camera3 objective0)
(supports camera3 colour)
(supports camera3 high_res)
(on_board camera4 rover0)
(calibration_target camera4 objective4)
(supports camera4 high_res)
(on_board camera5 rover9)
(calibration_target camera5 objective4)
(supports camera5 high_res)
(supports camera5 low_res)
(on_board camera6 rover1)
(calibration_target camera6 objective3)
(supports camera6 high_res)
(supports camera6 low_res)
(visible_from objective0 waypoint0)
(visible_from objective0 waypoint1)
(visible_from objective0 waypoint2)
(visible_from objective0 waypoint3)
(visible_from objective0 waypoint4)
(visible_from objective0 waypoint5)
(visible_from objective0 waypoint6)
(visible_from objective0 waypoint7)
(visible_from objective0 waypoint8)
(visible_from objective0 waypoint9)
(visible_from objective0 waypoint10)
(visible_from objective0 waypoint11)
(visible_from objective0 waypoint12)
(visible_from objective0 waypoint13)
(visible_from objective0 waypoint14)
(visible_from objective0 waypoint15)
(visible_from objective0 waypoint16)
(visible_from objective1 waypoint0)
(visible_from objective1 waypoint1)
(visible_from objective1 waypoint2)
(visible_from objective1 waypoint3)
(visible_from objective1 waypoint4)
(visible_from objective1 waypoint5)
(visible_from objective1 waypoint6)
(visible_from objective1 waypoint7)
(visible_from objective1 waypoint8)
(visible_from objective1 waypoint9)
(visible_from objective1 waypoint10)
(visible_from objective1 waypoint11)
(visible_from objective1 waypoint12)
(visible_from objective1 waypoint13)
(visible_from objective1 waypoint14)
(visible_from objective1 waypoint15)
(visible_from objective1 waypoint16)
(visible_from objective1 waypoint17)
(visible_from objective1 waypoint18)
(visible_from objective1 waypoint19)
(visible_from objective1 waypoint20)
(visible_from objective1 waypoint21)
(visible_from objective1 waypoint22)
(visible_from objective1 waypoint23)
(visible_from objective1 waypoint24)
(visible_from objective1 waypoint25)
(visible_from objective1 waypoint26)
(visible_from objective2 waypoint0)
(visible_from objective2 waypoint1)
(visible_from objective2 waypoint2)
(visible_from objective2 waypoint3)
(visible_from objective2 waypoint4)
(visible_from objective2 waypoint5)
(visible_from objective2 waypoint6)
(visible_from objective3 waypoint0)
(visible_from objective3 waypoint1)
(visible_from objective3 waypoint2)
(visible_from objective3 waypoint3)
(visible_from objective4 waypoint0)
(visible_from objective4 waypoint1)
(visible_from objective4 waypoint2)
(visible_from objective4 waypoint3)
(visible_from objective4 waypoint4)
(visible_from objective5 waypoint0)
(visible_from objective5 waypoint1)
(visible_from objective5 waypoint2)
(visible_from objective5 waypoint3)
(visible_from objective5 waypoint4)
(visible_from objective5 waypoint5)
(visible_from objective5 waypoint6)
(visible_from objective5 waypoint7)
(visible_from objective5 waypoint8)
(visible_from objective5 waypoint9)
(visible_from objective5 waypoint10)
(visible_from objective5 waypoint11)
(visible_from objective5 waypoint12)
(visible_from objective5 waypoint13)
(visible_from objective5 waypoint14)
(visible_from objective5 waypoint15)
(visible_from objective5 waypoint16)
(visible_from objective5 waypoint17)
(visible_from objective5 waypoint18)
(visible_from objective5 waypoint19)
(visible_from objective5 waypoint20)
(visible_from objective5 waypoint21)
(visible_from objective5 waypoint22)
(visible_from objective5 waypoint23)
(visible_from objective5 waypoint24)
(visible_from objective5 waypoint25)
(visible_from objective5 waypoint26)
(visible_from objective5 waypoint27)
(visible_from objective5 waypoint28)
(visible_from objective5 waypoint29)
(K-obj rover8 rover7store)
(K-obj rover8 rover3store)
(K-obj rover8 rover4store)
(K-obj rover8 rover9store)
(K-obj rover8 high_res)
(K-obj rover8 rover2store)
(K-obj rover8 low_res)
(K-obj rover8 rover5store)
(K-obj rover8 objective1)
(K-obj rover8 objective0)
(K-obj rover8 objective3)
(K-obj rover8 objective2)
(K-obj rover8 objective5)
(K-obj rover8 objective4)
(K-obj rover8 camera0)
(K-obj rover8 rover8store)
(K-obj rover8 camera1)
(K-obj rover8 waypoint12)
(K-obj rover8 camera3)
(K-obj rover8 camera2)
(K-obj rover8 rover0store)
(K-obj rover8 general)
(K-obj rover8 camera6)
(K-obj rover8 rover6store)
(K-obj rover8 waypoint25)
(K-obj rover8 waypoint24)
(K-obj rover8 waypoint27)
(K-obj rover8 waypoint26)
(K-obj rover8 waypoint21)
(K-obj rover8 waypoint20)
(K-obj rover8 waypoint23)
(K-obj rover8 waypoint22)
(K-obj rover8 waypoint29)
(K-obj rover8 waypoint28)
(K-obj rover8 camera4)
(K-obj rover8 waypoint8)
(K-obj rover8 waypoint9)
(K-obj rover8 waypoint6)
(K-obj rover8 waypoint7)
(K-obj rover8 waypoint4)
(K-obj rover8 waypoint5)
(K-obj rover8 waypoint2)
(K-obj rover8 waypoint3)
(K-obj rover8 waypoint0)
(K-obj rover8 waypoint1)
(K-obj rover8 waypoint18)
(K-obj rover8 waypoint19)
(K-obj rover8 camera5)
(K-obj rover8 waypoint10)
(K-obj rover8 waypoint11)
(K-obj rover8 colour)
(K-obj rover8 waypoint13)
(K-obj rover8 waypoint14)
(K-obj rover8 waypoint15)
(K-obj rover8 waypoint16)
(K-obj rover8 waypoint17)
(K-obj rover8 rover1store)
(K-obj rover9 rover7store)
(K-obj rover9 rover3store)
(K-obj rover9 rover4store)
(K-obj rover9 rover9store)
(K-obj rover9 high_res)
(K-obj rover9 rover2store)
(K-obj rover9 low_res)
(K-obj rover9 rover5store)
(K-obj rover9 objective1)
(K-obj rover9 objective0)
(K-obj rover9 objective3)
(K-obj rover9 objective2)
(K-obj rover9 objective5)
(K-obj rover9 objective4)
(K-obj rover9 camera0)
(K-obj rover9 rover8store)
(K-obj rover9 camera1)
(K-obj rover9 waypoint12)
(K-obj rover9 camera3)
(K-obj rover9 camera2)
(K-obj rover9 rover0store)
(K-obj rover9 general)
(K-obj rover9 camera6)
(K-obj rover9 rover6store)
(K-obj rover9 waypoint25)
(K-obj rover9 waypoint24)
(K-obj rover9 waypoint27)
(K-obj rover9 waypoint26)
(K-obj rover9 waypoint21)
(K-obj rover9 waypoint20)
(K-obj rover9 waypoint23)
(K-obj rover9 waypoint22)
(K-obj rover9 waypoint29)
(K-obj rover9 waypoint28)
(K-obj rover9 camera4)
(K-obj rover9 waypoint8)
(K-obj rover9 waypoint9)
(K-obj rover9 waypoint6)
(K-obj rover9 waypoint7)
(K-obj rover9 waypoint4)
(K-obj rover9 waypoint5)
(K-obj rover9 waypoint2)
(K-obj rover9 waypoint3)
(K-obj rover9 waypoint0)
(K-obj rover9 waypoint1)
(K-obj rover9 waypoint18)
(K-obj rover9 waypoint19)
(K-obj rover9 camera5)
(K-obj rover9 waypoint10)
(K-obj rover9 waypoint11)
(K-obj rover9 colour)
(K-obj rover9 waypoint13)
(K-obj rover9 waypoint14)
(K-obj rover9 waypoint15)
(K-obj rover9 waypoint16)
(K-obj rover9 waypoint17)
(K-obj rover9 rover1store)
(K-obj rover2 rover7store)
(K-obj rover2 rover3store)
(K-obj rover2 rover4store)
(K-obj rover2 rover9store)
(K-obj rover2 high_res)
(K-obj rover2 rover2store)
(K-obj rover2 low_res)
(K-obj rover2 rover5store)
(K-obj rover2 objective1)
(K-obj rover2 objective0)
(K-obj rover2 objective3)
(K-obj rover2 objective2)
(K-obj rover2 objective5)
(K-obj rover2 objective4)
(K-obj rover2 camera0)
(K-obj rover2 rover8store)
(K-obj rover2 camera1)
(K-obj rover2 waypoint12)
(K-obj rover2 camera3)
(K-obj rover2 camera2)
(K-obj rover2 rover0store)
(K-obj rover2 general)
(K-obj rover2 camera6)
(K-obj rover2 rover6store)
(K-obj rover2 waypoint25)
(K-obj rover2 waypoint24)
(K-obj rover2 waypoint27)
(K-obj rover2 waypoint26)
(K-obj rover2 waypoint21)
(K-obj rover2 waypoint20)
(K-obj rover2 waypoint23)
(K-obj rover2 waypoint22)
(K-obj rover2 waypoint29)
(K-obj rover2 waypoint28)
(K-obj rover2 camera4)
(K-obj rover2 waypoint8)
(K-obj rover2 waypoint9)
(K-obj rover2 waypoint6)
(K-obj rover2 waypoint7)
(K-obj rover2 waypoint4)
(K-obj rover2 waypoint5)
(K-obj rover2 waypoint2)
(K-obj rover2 waypoint3)
(K-obj rover2 waypoint0)
(K-obj rover2 waypoint1)
(K-obj rover2 waypoint18)
(K-obj rover2 waypoint19)
(K-obj rover2 camera5)
(K-obj rover2 waypoint10)
(K-obj rover2 waypoint11)
(K-obj rover2 colour)
(K-obj rover2 waypoint13)
(K-obj rover2 waypoint14)
(K-obj rover2 waypoint15)
(K-obj rover2 waypoint16)
(K-obj rover2 waypoint17)
(K-obj rover2 rover1store)
(K-obj rover3 rover7store)
(K-obj rover3 rover3store)
(K-obj rover3 rover4store)
(K-obj rover3 rover9store)
(K-obj rover3 high_res)
(K-obj rover3 rover2store)
(K-obj rover3 low_res)
(K-obj rover3 rover5store)
(K-obj rover3 objective1)
(K-obj rover3 objective0)
(K-obj rover3 objective3)
(K-obj rover3 objective2)
(K-obj rover3 objective5)
(K-obj rover3 objective4)
(K-obj rover3 camera0)
(K-obj rover3 rover8store)
(K-obj rover3 camera1)
(K-obj rover3 waypoint12)
(K-obj rover3 camera3)
(K-obj rover3 camera2)
(K-obj rover3 rover0store)
(K-obj rover3 general)
(K-obj rover3 camera6)
(K-obj rover3 rover6store)
(K-obj rover3 waypoint25)
(K-obj rover3 waypoint24)
(K-obj rover3 waypoint27)
(K-obj rover3 waypoint26)
(K-obj rover3 waypoint21)
(K-obj rover3 waypoint20)
(K-obj rover3 waypoint23)
(K-obj rover3 waypoint22)
(K-obj rover3 waypoint29)
(K-obj rover3 waypoint28)
(K-obj rover3 camera4)
(K-obj rover3 waypoint8)
(K-obj rover3 waypoint9)
(K-obj rover3 waypoint6)
(K-obj rover3 waypoint7)
(K-obj rover3 waypoint4)
(K-obj rover3 waypoint5)
(K-obj rover3 waypoint2)
(K-obj rover3 waypoint3)
(K-obj rover3 waypoint0)
(K-obj rover3 waypoint1)
(K-obj rover3 waypoint18)
(K-obj rover3 waypoint19)
(K-obj rover3 camera5)
(K-obj rover3 waypoint10)
(K-obj rover3 waypoint11)
(K-obj rover3 colour)
(K-obj rover3 waypoint13)
(K-obj rover3 waypoint14)
(K-obj rover3 waypoint15)
(K-obj rover3 waypoint16)
(K-obj rover3 waypoint17)
(K-obj rover3 rover1store)
(K-obj rover0 rover7store)
(K-obj rover0 rover3store)
(K-obj rover0 rover4store)
(K-obj rover0 rover9store)
(K-obj rover0 high_res)
(K-obj rover0 rover2store)
(K-obj rover0 low_res)
(K-obj rover0 rover5store)
(K-obj rover0 objective1)
(K-obj rover0 objective0)
(K-obj rover0 objective3)
(K-obj rover0 objective2)
(K-obj rover0 objective5)
(K-obj rover0 objective4)
(K-obj rover0 camera0)
(K-obj rover0 rover8store)
(K-obj rover0 camera1)
(K-obj rover0 waypoint12)
(K-obj rover0 camera3)
(K-obj rover0 camera2)
(K-obj rover0 rover0store)
(K-obj rover0 general)
(K-obj rover0 camera6)
(K-obj rover0 rover6store)
(K-obj rover0 waypoint25)
(K-obj rover0 waypoint24)
(K-obj rover0 waypoint27)
(K-obj rover0 waypoint26)
(K-obj rover0 waypoint21)
(K-obj rover0 waypoint20)
(K-obj rover0 waypoint23)
(K-obj rover0 waypoint22)
(K-obj rover0 waypoint29)
(K-obj rover0 waypoint28)
(K-obj rover0 camera4)
(K-obj rover0 waypoint8)
(K-obj rover0 waypoint9)
(K-obj rover0 waypoint6)
(K-obj rover0 waypoint7)
(K-obj rover0 waypoint4)
(K-obj rover0 waypoint5)
(K-obj rover0 waypoint2)
(K-obj rover0 waypoint3)
(K-obj rover0 waypoint0)
(K-obj rover0 waypoint1)
(K-obj rover0 waypoint18)
(K-obj rover0 waypoint19)
(K-obj rover0 camera5)
(K-obj rover0 waypoint10)
(K-obj rover0 waypoint11)
(K-obj rover0 colour)
(K-obj rover0 waypoint13)
(K-obj rover0 waypoint14)
(K-obj rover0 waypoint15)
(K-obj rover0 waypoint16)
(K-obj rover0 waypoint17)
(K-obj rover0 rover1store)
(K-obj rover1 rover7store)
(K-obj rover1 rover3store)
(K-obj rover1 rover4store)
(K-obj rover1 rover9store)
(K-obj rover1 high_res)
(K-obj rover1 rover2store)
(K-obj rover1 low_res)
(K-obj rover1 rover5store)
(K-obj rover1 objective1)
(K-obj rover1 objective0)
(K-obj rover1 objective3)
(K-obj rover1 objective2)
(K-obj rover1 objective5)
(K-obj rover1 objective4)
(K-obj rover1 camera0)
(K-obj rover1 rover8store)
(K-obj rover1 camera1)
(K-obj rover1 waypoint12)
(K-obj rover1 camera3)
(K-obj rover1 camera2)
(K-obj rover1 rover0store)
(K-obj rover1 general)
(K-obj rover1 camera6)
(K-obj rover1 rover6store)
(K-obj rover1 waypoint25)
(K-obj rover1 waypoint24)
(K-obj rover1 waypoint27)
(K-obj rover1 waypoint26)
(K-obj rover1 waypoint21)
(K-obj rover1 waypoint20)
(K-obj rover1 waypoint23)
(K-obj rover1 waypoint22)
(K-obj rover1 waypoint29)
(K-obj rover1 waypoint28)
(K-obj rover1 camera4)
(K-obj rover1 waypoint8)
(K-obj rover1 waypoint9)
(K-obj rover1 waypoint6)
(K-obj rover1 waypoint7)
(K-obj rover1 waypoint4)
(K-obj rover1 waypoint5)
(K-obj rover1 waypoint2)
(K-obj rover1 waypoint3)
(K-obj rover1 waypoint0)
(K-obj rover1 waypoint1)
(K-obj rover1 waypoint18)
(K-obj rover1 waypoint19)
(K-obj rover1 camera5)
(K-obj rover1 waypoint10)
(K-obj rover1 waypoint11)
(K-obj rover1 colour)
(K-obj rover1 waypoint13)
(K-obj rover1 waypoint14)
(K-obj rover1 waypoint15)
(K-obj rover1 waypoint16)
(K-obj rover1 waypoint17)
(K-obj rover1 rover1store)
(K-obj rover6 rover7store)
(K-obj rover6 rover3store)
(K-obj rover6 rover4store)
(K-obj rover6 rover9store)
(K-obj rover6 high_res)
(K-obj rover6 rover2store)
(K-obj rover6 low_res)
(K-obj rover6 rover5store)
(K-obj rover6 objective1)
(K-obj rover6 objective0)
(K-obj rover6 objective3)
(K-obj rover6 objective2)
(K-obj rover6 objective5)
(K-obj rover6 objective4)
(K-obj rover6 camera0)
(K-obj rover6 rover8store)
(K-obj rover6 camera1)
(K-obj rover6 waypoint12)
(K-obj rover6 camera3)
(K-obj rover6 camera2)
(K-obj rover6 rover0store)
(K-obj rover6 general)
(K-obj rover6 camera6)
(K-obj rover6 rover6store)
(K-obj rover6 waypoint25)
(K-obj rover6 waypoint24)
(K-obj rover6 waypoint27)
(K-obj rover6 waypoint26)
(K-obj rover6 waypoint21)
(K-obj rover6 waypoint20)
(K-obj rover6 waypoint23)
(K-obj rover6 waypoint22)
(K-obj rover6 waypoint29)
(K-obj rover6 waypoint28)
(K-obj rover6 camera4)
(K-obj rover6 waypoint8)
(K-obj rover6 waypoint9)
(K-obj rover6 waypoint6)
(K-obj rover6 waypoint7)
(K-obj rover6 waypoint4)
(K-obj rover6 waypoint5)
(K-obj rover6 waypoint2)
(K-obj rover6 waypoint3)
(K-obj rover6 waypoint0)
(K-obj rover6 waypoint1)
(K-obj rover6 waypoint18)
(K-obj rover6 waypoint19)
(K-obj rover6 camera5)
(K-obj rover6 waypoint10)
(K-obj rover6 waypoint11)
(K-obj rover6 colour)
(K-obj rover6 waypoint13)
(K-obj rover6 waypoint14)
(K-obj rover6 waypoint15)
(K-obj rover6 waypoint16)
(K-obj rover6 waypoint17)
(K-obj rover6 rover1store)
(K-obj rover7 rover7store)
(K-obj rover7 rover3store)
(K-obj rover7 rover4store)
(K-obj rover7 rover9store)
(K-obj rover7 high_res)
(K-obj rover7 rover2store)
(K-obj rover7 low_res)
(K-obj rover7 rover5store)
(K-obj rover7 objective1)
(K-obj rover7 objective0)
(K-obj rover7 objective3)
(K-obj rover7 objective2)
(K-obj rover7 objective5)
(K-obj rover7 objective4)
(K-obj rover7 camera0)
(K-obj rover7 rover8store)
(K-obj rover7 camera1)
(K-obj rover7 waypoint12)
(K-obj rover7 camera3)
(K-obj rover7 camera2)
(K-obj rover7 rover0store)
(K-obj rover7 general)
(K-obj rover7 camera6)
(K-obj rover7 rover6store)
(K-obj rover7 waypoint25)
(K-obj rover7 waypoint24)
(K-obj rover7 waypoint27)
(K-obj rover7 waypoint26)
(K-obj rover7 waypoint21)
(K-obj rover7 waypoint20)
(K-obj rover7 waypoint23)
(K-obj rover7 waypoint22)
(K-obj rover7 waypoint29)
(K-obj rover7 waypoint28)
(K-obj rover7 camera4)
(K-obj rover7 waypoint8)
(K-obj rover7 waypoint9)
(K-obj rover7 waypoint6)
(K-obj rover7 waypoint7)
(K-obj rover7 waypoint4)
(K-obj rover7 waypoint5)
(K-obj rover7 waypoint2)
(K-obj rover7 waypoint3)
(K-obj rover7 waypoint0)
(K-obj rover7 waypoint1)
(K-obj rover7 waypoint18)
(K-obj rover7 waypoint19)
(K-obj rover7 camera5)
(K-obj rover7 waypoint10)
(K-obj rover7 waypoint11)
(K-obj rover7 colour)
(K-obj rover7 waypoint13)
(K-obj rover7 waypoint14)
(K-obj rover7 waypoint15)
(K-obj rover7 waypoint16)
(K-obj rover7 waypoint17)
(K-obj rover7 rover1store)
(K-obj rover4 rover7store)
(K-obj rover4 rover3store)
(K-obj rover4 rover4store)
(K-obj rover4 rover9store)
(K-obj rover4 high_res)
(K-obj rover4 rover2store)
(K-obj rover4 low_res)
(K-obj rover4 rover5store)
(K-obj rover4 objective1)
(K-obj rover4 objective0)
(K-obj rover4 objective3)
(K-obj rover4 objective2)
(K-obj rover4 objective5)
(K-obj rover4 objective4)
(K-obj rover4 camera0)
(K-obj rover4 rover8store)
(K-obj rover4 camera1)
(K-obj rover4 waypoint12)
(K-obj rover4 camera3)
(K-obj rover4 camera2)
(K-obj rover4 rover0store)
(K-obj rover4 general)
(K-obj rover4 camera6)
(K-obj rover4 rover6store)
(K-obj rover4 waypoint25)
(K-obj rover4 waypoint24)
(K-obj rover4 waypoint27)
(K-obj rover4 waypoint26)
(K-obj rover4 waypoint21)
(K-obj rover4 waypoint20)
(K-obj rover4 waypoint23)
(K-obj rover4 waypoint22)
(K-obj rover4 waypoint29)
(K-obj rover4 waypoint28)
(K-obj rover4 camera4)
(K-obj rover4 waypoint8)
(K-obj rover4 waypoint9)
(K-obj rover4 waypoint6)
(K-obj rover4 waypoint7)
(K-obj rover4 waypoint4)
(K-obj rover4 waypoint5)
(K-obj rover4 waypoint2)
(K-obj rover4 waypoint3)
(K-obj rover4 waypoint0)
(K-obj rover4 waypoint1)
(K-obj rover4 waypoint18)
(K-obj rover4 waypoint19)
(K-obj rover4 camera5)
(K-obj rover4 waypoint10)
(K-obj rover4 waypoint11)
(K-obj rover4 colour)
(K-obj rover4 waypoint13)
(K-obj rover4 waypoint14)
(K-obj rover4 waypoint15)
(K-obj rover4 waypoint16)
(K-obj rover4 waypoint17)
(K-obj rover4 rover1store)
(K-obj rover5 rover7store)
(K-obj rover5 rover3store)
(K-obj rover5 rover4store)
(K-obj rover5 rover9store)
(K-obj rover5 high_res)
(K-obj rover5 rover2store)
(K-obj rover5 low_res)
(K-obj rover5 rover5store)
(K-obj rover5 objective1)
(K-obj rover5 objective0)
(K-obj rover5 objective3)
(K-obj rover5 objective2)
(K-obj rover5 objective5)
(K-obj rover5 objective4)
(K-obj rover5 camera0)
(K-obj rover5 rover8store)
(K-obj rover5 camera1)
(K-obj rover5 waypoint12)
(K-obj rover5 camera3)
(K-obj rover5 camera2)
(K-obj rover5 rover0store)
(K-obj rover5 general)
(K-obj rover5 camera6)
(K-obj rover5 rover6store)
(K-obj rover5 waypoint25)
(K-obj rover5 waypoint24)
(K-obj rover5 waypoint27)
(K-obj rover5 waypoint26)
(K-obj rover5 waypoint21)
(K-obj rover5 waypoint20)
(K-obj rover5 waypoint23)
(K-obj rover5 waypoint22)
(K-obj rover5 waypoint29)
(K-obj rover5 waypoint28)
(K-obj rover5 camera4)
(K-obj rover5 waypoint8)
(K-obj rover5 waypoint9)
(K-obj rover5 waypoint6)
(K-obj rover5 waypoint7)
(K-obj rover5 waypoint4)
(K-obj rover5 waypoint5)
(K-obj rover5 waypoint2)
(K-obj rover5 waypoint3)
(K-obj rover5 waypoint0)
(K-obj rover5 waypoint1)
(K-obj rover5 waypoint18)
(K-obj rover5 waypoint19)
(K-obj rover5 camera5)
(K-obj rover5 waypoint10)
(K-obj rover5 waypoint11)
(K-obj rover5 colour)
(K-obj rover5 waypoint13)
(K-obj rover5 waypoint14)
(K-obj rover5 waypoint15)
(K-obj rover5 waypoint16)
(K-obj rover5 waypoint17)
(K-obj rover5 rover1store)
(K-obj rover8 rover8)
(K-obj rover9 rover9)
(K-obj rover2 rover2)
(K-obj rover3 rover3)
(K-obj rover0 rover0)
(K-obj rover1 rover1)
(K-obj rover6 rover6)
(K-obj rover7 rover7)
(K-obj rover4 rover4)
(K-obj rover5 rover5)
(K-ag-pred rover8 pred--at)
(K-ag-pred rover8 pred--can_traverse)
(K-ag-pred rover8 pred--equipped_for_soil_analysis)
(K-ag-pred rover8 pred--equipped_for_rock_analysis)
(K-ag-pred rover8 pred--equipped_for_imaging)
(K-ag-pred rover8 pred--have_rock_analysis)
(K-ag-pred rover8 pred--have_soil_analysis)
(K-ag-pred rover8 pred--calibrated)
(K-ag-pred rover8 pred--available)
(K-ag-pred rover8 pred--have_image)
(K-ag-pred rover8 pred--store_of)
(K-ag-pred rover8 pred--on_board)
(K-ag-pred rover9 pred--at)
(K-ag-pred rover9 pred--can_traverse)
(K-ag-pred rover9 pred--equipped_for_soil_analysis)
(K-ag-pred rover9 pred--equipped_for_rock_analysis)
(K-ag-pred rover9 pred--equipped_for_imaging)
(K-ag-pred rover9 pred--have_rock_analysis)
(K-ag-pred rover9 pred--have_soil_analysis)
(K-ag-pred rover9 pred--calibrated)
(K-ag-pred rover9 pred--available)
(K-ag-pred rover9 pred--have_image)
(K-ag-pred rover9 pred--store_of)
(K-ag-pred rover9 pred--on_board)
(K-ag-pred rover2 pred--at)
(K-ag-pred rover2 pred--can_traverse)
(K-ag-pred rover2 pred--equipped_for_soil_analysis)
(K-ag-pred rover2 pred--equipped_for_rock_analysis)
(K-ag-pred rover2 pred--equipped_for_imaging)
(K-ag-pred rover2 pred--have_rock_analysis)
(K-ag-pred rover2 pred--have_soil_analysis)
(K-ag-pred rover2 pred--calibrated)
(K-ag-pred rover2 pred--available)
(K-ag-pred rover2 pred--have_image)
(K-ag-pred rover2 pred--store_of)
(K-ag-pred rover2 pred--on_board)
(K-ag-pred rover3 pred--at)
(K-ag-pred rover3 pred--can_traverse)
(K-ag-pred rover3 pred--equipped_for_soil_analysis)
(K-ag-pred rover3 pred--equipped_for_rock_analysis)
(K-ag-pred rover3 pred--equipped_for_imaging)
(K-ag-pred rover3 pred--have_rock_analysis)
(K-ag-pred rover3 pred--have_soil_analysis)
(K-ag-pred rover3 pred--calibrated)
(K-ag-pred rover3 pred--available)
(K-ag-pred rover3 pred--have_image)
(K-ag-pred rover3 pred--store_of)
(K-ag-pred rover3 pred--on_board)
(K-ag-pred rover0 pred--at)
(K-ag-pred rover0 pred--can_traverse)
(K-ag-pred rover0 pred--equipped_for_soil_analysis)
(K-ag-pred rover0 pred--equipped_for_rock_analysis)
(K-ag-pred rover0 pred--equipped_for_imaging)
(K-ag-pred rover0 pred--have_rock_analysis)
(K-ag-pred rover0 pred--have_soil_analysis)
(K-ag-pred rover0 pred--calibrated)
(K-ag-pred rover0 pred--available)
(K-ag-pred rover0 pred--have_image)
(K-ag-pred rover0 pred--store_of)
(K-ag-pred rover0 pred--on_board)
(K-ag-pred rover1 pred--at)
(K-ag-pred rover1 pred--can_traverse)
(K-ag-pred rover1 pred--equipped_for_soil_analysis)
(K-ag-pred rover1 pred--equipped_for_rock_analysis)
(K-ag-pred rover1 pred--equipped_for_imaging)
(K-ag-pred rover1 pred--have_rock_analysis)
(K-ag-pred rover1 pred--have_soil_analysis)
(K-ag-pred rover1 pred--calibrated)
(K-ag-pred rover1 pred--available)
(K-ag-pred rover1 pred--have_image)
(K-ag-pred rover1 pred--store_of)
(K-ag-pred rover1 pred--on_board)
(K-ag-pred rover6 pred--at)
(K-ag-pred rover6 pred--can_traverse)
(K-ag-pred rover6 pred--equipped_for_soil_analysis)
(K-ag-pred rover6 pred--equipped_for_rock_analysis)
(K-ag-pred rover6 pred--equipped_for_imaging)
(K-ag-pred rover6 pred--have_rock_analysis)
(K-ag-pred rover6 pred--have_soil_analysis)
(K-ag-pred rover6 pred--calibrated)
(K-ag-pred rover6 pred--available)
(K-ag-pred rover6 pred--have_image)
(K-ag-pred rover6 pred--store_of)
(K-ag-pred rover6 pred--on_board)
(K-ag-pred rover7 pred--at)
(K-ag-pred rover7 pred--can_traverse)
(K-ag-pred rover7 pred--equipped_for_soil_analysis)
(K-ag-pred rover7 pred--equipped_for_rock_analysis)
(K-ag-pred rover7 pred--equipped_for_imaging)
(K-ag-pred rover7 pred--have_rock_analysis)
(K-ag-pred rover7 pred--have_soil_analysis)
(K-ag-pred rover7 pred--calibrated)
(K-ag-pred rover7 pred--available)
(K-ag-pred rover7 pred--have_image)
(K-ag-pred rover7 pred--store_of)
(K-ag-pred rover7 pred--on_board)
(K-ag-pred rover4 pred--at)
(K-ag-pred rover4 pred--can_traverse)
(K-ag-pred rover4 pred--equipped_for_soil_analysis)
(K-ag-pred rover4 pred--equipped_for_rock_analysis)
(K-ag-pred rover4 pred--equipped_for_imaging)
(K-ag-pred rover4 pred--have_rock_analysis)
(K-ag-pred rover4 pred--have_soil_analysis)
(K-ag-pred rover4 pred--calibrated)
(K-ag-pred rover4 pred--available)
(K-ag-pred rover4 pred--have_image)
(K-ag-pred rover4 pred--store_of)
(K-ag-pred rover4 pred--on_board)
(K-ag-pred rover5 pred--at)
(K-ag-pred rover5 pred--can_traverse)
(K-ag-pred rover5 pred--equipped_for_soil_analysis)
(K-ag-pred rover5 pred--equipped_for_rock_analysis)
(K-ag-pred rover5 pred--equipped_for_imaging)
(K-ag-pred rover5 pred--have_rock_analysis)
(K-ag-pred rover5 pred--have_soil_analysis)
(K-ag-pred rover5 pred--calibrated)
(K-ag-pred rover5 pred--available)
(K-ag-pred rover5 pred--have_image)
(K-ag-pred rover5 pred--store_of)
(K-ag-pred rover5 pred--on_board)
(K-ag-pred rover8 pred--visible)
(K-pred rover8 pred--visible)
(K-ag-pred rover9 pred--visible)
(K-pred rover9 pred--visible)
(K-ag-pred rover2 pred--visible)
(K-pred rover2 pred--visible)
(K-ag-pred rover3 pred--visible)
(K-pred rover3 pred--visible)
(K-ag-pred rover0 pred--visible)
(K-pred rover0 pred--visible)
(K-ag-pred rover1 pred--visible)
(K-pred rover1 pred--visible)
(K-ag-pred rover6 pred--visible)
(K-pred rover6 pred--visible)
(K-ag-pred rover7 pred--visible)
(K-pred rover7 pred--visible)
(K-ag-pred rover4 pred--visible)
(K-pred rover4 pred--visible)
(K-ag-pred rover5 pred--visible)
(K-pred rover5 pred--visible)
(K-ag-pred rover8 pred--visible_from)
(K-pred rover8 pred--visible_from)
(K-ag-pred rover9 pred--visible_from)
(K-pred rover9 pred--visible_from)
(K-ag-pred rover2 pred--visible_from)
(K-pred rover2 pred--visible_from)
(K-ag-pred rover3 pred--visible_from)
(K-pred rover3 pred--visible_from)
(K-ag-pred rover0 pred--visible_from)
(K-pred rover0 pred--visible_from)
(K-ag-pred rover1 pred--visible_from)
(K-pred rover1 pred--visible_from)
(K-ag-pred rover6 pred--visible_from)
(K-pred rover6 pred--visible_from)
(K-ag-pred rover7 pred--visible_from)
(K-pred rover7 pred--visible_from)
(K-ag-pred rover4 pred--visible_from)
(K-pred rover4 pred--visible_from)
(K-ag-pred rover5 pred--visible_from)
(K-pred rover5 pred--visible_from)
(K-ag-pred rover8 pred--at_rock_sample)
(K-pred rover8 pred--at_rock_sample)
(K-ag-pred rover9 pred--at_rock_sample)
(K-pred rover9 pred--at_rock_sample)
(K-ag-pred rover2 pred--at_rock_sample)
(K-pred rover2 pred--at_rock_sample)
(K-ag-pred rover3 pred--at_rock_sample)
(K-pred rover3 pred--at_rock_sample)
(K-ag-pred rover0 pred--at_rock_sample)
(K-pred rover0 pred--at_rock_sample)
(K-ag-pred rover1 pred--at_rock_sample)
(K-pred rover1 pred--at_rock_sample)
(K-ag-pred rover6 pred--at_rock_sample)
(K-pred rover6 pred--at_rock_sample)
(K-ag-pred rover7 pred--at_rock_sample)
(K-pred rover7 pred--at_rock_sample)
(K-ag-pred rover4 pred--at_rock_sample)
(K-pred rover4 pred--at_rock_sample)
(K-ag-pred rover5 pred--at_rock_sample)
(K-pred rover5 pred--at_rock_sample)
(K-ag-pred rover8 pred--at_soil_sample)
(K-pred rover8 pred--at_soil_sample)
(K-ag-pred rover9 pred--at_soil_sample)
(K-pred rover9 pred--at_soil_sample)
(K-ag-pred rover2 pred--at_soil_sample)
(K-pred rover2 pred--at_soil_sample)
(K-ag-pred rover3 pred--at_soil_sample)
(K-pred rover3 pred--at_soil_sample)
(K-ag-pred rover0 pred--at_soil_sample)
(K-pred rover0 pred--at_soil_sample)
(K-ag-pred rover1 pred--at_soil_sample)
(K-pred rover1 pred--at_soil_sample)
(K-ag-pred rover6 pred--at_soil_sample)
(K-pred rover6 pred--at_soil_sample)
(K-ag-pred rover7 pred--at_soil_sample)
(K-pred rover7 pred--at_soil_sample)
(K-ag-pred rover4 pred--at_soil_sample)
(K-pred rover4 pred--at_soil_sample)
(K-ag-pred rover5 pred--at_soil_sample)
(K-pred rover5 pred--at_soil_sample)
(K-ag-pred rover8 pred--at_lander)
(K-pred rover8 pred--at_lander)
(K-ag-pred rover9 pred--at_lander)
(K-pred rover9 pred--at_lander)
(K-ag-pred rover2 pred--at_lander)
(K-pred rover2 pred--at_lander)
(K-ag-pred rover3 pred--at_lander)
(K-pred rover3 pred--at_lander)
(K-ag-pred rover0 pred--at_lander)
(K-pred rover0 pred--at_lander)
(K-ag-pred rover1 pred--at_lander)
(K-pred rover1 pred--at_lander)
(K-ag-pred rover6 pred--at_lander)
(K-pred rover6 pred--at_lander)
(K-ag-pred rover7 pred--at_lander)
(K-pred rover7 pred--at_lander)
(K-ag-pred rover4 pred--at_lander)
(K-pred rover4 pred--at_lander)
(K-ag-pred rover5 pred--at_lander)
(K-pred rover5 pred--at_lander)
(K-ag-pred rover8 pred--communicated_image_data)
(K-pred rover8 pred--communicated_image_data)
(K-ag-pred rover9 pred--communicated_image_data)
(K-pred rover9 pred--communicated_image_data)
(K-ag-pred rover2 pred--communicated_image_data)
(K-pred rover2 pred--communicated_image_data)
(K-ag-pred rover3 pred--communicated_image_data)
(K-pred rover3 pred--communicated_image_data)
(K-ag-pred rover0 pred--communicated_image_data)
(K-pred rover0 pred--communicated_image_data)
(K-ag-pred rover1 pred--communicated_image_data)
(K-pred rover1 pred--communicated_image_data)
(K-ag-pred rover6 pred--communicated_image_data)
(K-pred rover6 pred--communicated_image_data)
(K-ag-pred rover7 pred--communicated_image_data)
(K-pred rover7 pred--communicated_image_data)
(K-ag-pred rover4 pred--communicated_image_data)
(K-pred rover4 pred--communicated_image_data)
(K-ag-pred rover5 pred--communicated_image_data)
(K-pred rover5 pred--communicated_image_data)
(K-ag-pred rover8 pred--communicated_rock_data)
(K-pred rover8 pred--communicated_rock_data)
(K-ag-pred rover9 pred--communicated_rock_data)
(K-pred rover9 pred--communicated_rock_data)
(K-ag-pred rover2 pred--communicated_rock_data)
(K-pred rover2 pred--communicated_rock_data)
(K-ag-pred rover3 pred--communicated_rock_data)
(K-pred rover3 pred--communicated_rock_data)
(K-ag-pred rover0 pred--communicated_rock_data)
(K-pred rover0 pred--communicated_rock_data)
(K-ag-pred rover1 pred--communicated_rock_data)
(K-pred rover1 pred--communicated_rock_data)
(K-ag-pred rover6 pred--communicated_rock_data)
(K-pred rover6 pred--communicated_rock_data)
(K-ag-pred rover7 pred--communicated_rock_data)
(K-pred rover7 pred--communicated_rock_data)
(K-ag-pred rover4 pred--communicated_rock_data)
(K-pred rover4 pred--communicated_rock_data)
(K-ag-pred rover5 pred--communicated_rock_data)
(K-pred rover5 pred--communicated_rock_data)
(K-ag-pred rover8 pred--communicated_soil_data)
(K-pred rover8 pred--communicated_soil_data)
(K-ag-pred rover9 pred--communicated_soil_data)
(K-pred rover9 pred--communicated_soil_data)
(K-ag-pred rover2 pred--communicated_soil_data)
(K-pred rover2 pred--communicated_soil_data)
(K-ag-pred rover3 pred--communicated_soil_data)
(K-pred rover3 pred--communicated_soil_data)
(K-ag-pred rover0 pred--communicated_soil_data)
(K-pred rover0 pred--communicated_soil_data)
(K-ag-pred rover1 pred--communicated_soil_data)
(K-pred rover1 pred--communicated_soil_data)
(K-ag-pred rover6 pred--communicated_soil_data)
(K-pred rover6 pred--communicated_soil_data)
(K-ag-pred rover7 pred--communicated_soil_data)
(K-pred rover7 pred--communicated_soil_data)
(K-ag-pred rover4 pred--communicated_soil_data)
(K-pred rover4 pred--communicated_soil_data)
(K-ag-pred rover5 pred--communicated_soil_data)
(K-pred rover5 pred--communicated_soil_data)
(K-ag-pred rover8 pred--empty)
(K-pred rover8 pred--empty)
(K-ag-pred rover9 pred--empty)
(K-pred rover9 pred--empty)
(K-ag-pred rover2 pred--empty)
(K-pred rover2 pred--empty)
(K-ag-pred rover3 pred--empty)
(K-pred rover3 pred--empty)
(K-ag-pred rover0 pred--empty)
(K-pred rover0 pred--empty)
(K-ag-pred rover1 pred--empty)
(K-pred rover1 pred--empty)
(K-ag-pred rover6 pred--empty)
(K-pred rover6 pred--empty)
(K-ag-pred rover7 pred--empty)
(K-pred rover7 pred--empty)
(K-ag-pred rover4 pred--empty)
(K-pred rover4 pred--empty)
(K-ag-pred rover5 pred--empty)
(K-pred rover5 pred--empty)
(K-ag-pred rover8 pred--full)
(K-pred rover8 pred--full)
(K-ag-pred rover9 pred--full)
(K-pred rover9 pred--full)
(K-ag-pred rover2 pred--full)
(K-pred rover2 pred--full)
(K-ag-pred rover3 pred--full)
(K-pred rover3 pred--full)
(K-ag-pred rover0 pred--full)
(K-pred rover0 pred--full)
(K-ag-pred rover1 pred--full)
(K-pred rover1 pred--full)
(K-ag-pred rover6 pred--full)
(K-pred rover6 pred--full)
(K-ag-pred rover7 pred--full)
(K-pred rover7 pred--full)
(K-ag-pred rover4 pred--full)
(K-pred rover4 pred--full)
(K-ag-pred rover5 pred--full)
(K-pred rover5 pred--full)
(K-ag-pred rover8 pred--supports)
(K-pred rover8 pred--supports)
(K-ag-pred rover9 pred--supports)
(K-pred rover9 pred--supports)
(K-ag-pred rover2 pred--supports)
(K-pred rover2 pred--supports)
(K-ag-pred rover3 pred--supports)
(K-pred rover3 pred--supports)
(K-ag-pred rover0 pred--supports)
(K-pred rover0 pred--supports)
(K-ag-pred rover1 pred--supports)
(K-pred rover1 pred--supports)
(K-ag-pred rover6 pred--supports)
(K-pred rover6 pred--supports)
(K-ag-pred rover7 pred--supports)
(K-pred rover7 pred--supports)
(K-ag-pred rover4 pred--supports)
(K-pred rover4 pred--supports)
(K-ag-pred rover5 pred--supports)
(K-pred rover5 pred--supports)
(K-ag-pred rover8 pred--calibration_target)
(K-pred rover8 pred--calibration_target)
(K-ag-pred rover9 pred--calibration_target)
(K-pred rover9 pred--calibration_target)
(K-ag-pred rover2 pred--calibration_target)
(K-pred rover2 pred--calibration_target)
(K-ag-pred rover3 pred--calibration_target)
(K-pred rover3 pred--calibration_target)
(K-ag-pred rover0 pred--calibration_target)
(K-pred rover0 pred--calibration_target)
(K-ag-pred rover1 pred--calibration_target)
(K-pred rover1 pred--calibration_target)
(K-ag-pred rover6 pred--calibration_target)
(K-pred rover6 pred--calibration_target)
(K-ag-pred rover7 pred--calibration_target)
(K-pred rover7 pred--calibration_target)
(K-ag-pred rover4 pred--calibration_target)
(K-pred rover4 pred--calibration_target)
(K-ag-pred rover5 pred--calibration_target)
(K-pred rover5 pred--calibration_target)
(K-ag-pred rover8 pred--channel_free)
(K-pred rover8 pred--channel_free)
(K-ag-pred rover9 pred--channel_free)
(K-pred rover9 pred--channel_free)
(K-ag-pred rover2 pred--channel_free)
(K-pred rover2 pred--channel_free)
(K-ag-pred rover3 pred--channel_free)
(K-pred rover3 pred--channel_free)
(K-ag-pred rover0 pred--channel_free)
(K-pred rover0 pred--channel_free)
(K-ag-pred rover1 pred--channel_free)
(K-pred rover1 pred--channel_free)
(K-ag-pred rover6 pred--channel_free)
(K-pred rover6 pred--channel_free)
(K-ag-pred rover7 pred--channel_free)
(K-pred rover7 pred--channel_free)
(K-ag-pred rover4 pred--channel_free)
(K-pred rover4 pred--channel_free)
(K-ag-pred rover5 pred--channel_free)
(K-pred rover5 pred--channel_free)
)
(:goal	(and (considered__available_ROVER0__59)
(communicated_soil_data waypoint24) (communicated_soil_data waypoint2) (communicated_soil_data waypoint1) (communicated_soil_data waypoint12) (communicated_soil_data waypoint11) (communicated_soil_data waypoint21) (communicated_soil_data waypoint3) (communicated_soil_data waypoint25) (communicated_rock_data waypoint6) (communicated_rock_data waypoint28) (communicated_rock_data waypoint20) (communicated_image_data objective2 low_res) (communicated_image_data objective1 high_res) (communicated_image_data objective3 high_res))
)
(:metric minimize (total-time))
)
